/* ============================================================
   Rickyedit Games — Lyrics Data
   Parsed from song lyrics for the Letrless game.
   ============================================================ */
window.RICKY_LYRICS = {
  "ir": [
    "Me considero buen chaval",
    "No me gusta mucho salir",
    "No suelo estar mal y a decir verdad",
    "No soy demasiado de sonreír",
    "¿Porqué me sale todo mal?",
    "¿Porqué no puedo ser feliz?",
    "¿Por qué me ha tocado aprender?",
    "Que amar también",
    "Es saber dejar ir",
    "Ir (oh, oh, oh, oh, oh, oh)",
    "Me considero buen chaval",
    "No me gusta mucho salir",
    "No suelo estar mal y a decir verdad",
    "No soy demasiado de sonreír",
    "¿Porqué me sale todo mal?",
    "¿Porqué no puedo ser feliz?",
    "Porque me ha tocado aprender",
    "Que amar también",
    "Es saber dejar ir",
    "Ir (oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh, oh)",
    "¿Porqué me sale todo mal?",
    "¿Porque no puedo ser feliz?",
    "¿Porqué me ha tocado aprender?"
  ],
  "si mañana": [
    "Vivo decisiones que se toman sin motivos",
    "Si contigo to’ parecen bendiciones",
    "Desde abajo to’ perdidos, confiados, convencidos",
    "De que to’ va a funcionar pero no sé",
    "Si mañana ya no somos nada",
    "Si mañana este mundo se acaba",
    "Dímelo cuando me pille volando",
    "To’ lo que prometimos en el aire flotando",
    "Vida sana pa’ que te quedaras",
    "Muchas ganas de verte la cara",
    "Sigo buscando, ese maldito mando",
    "Que ponga fin a to’ lo que nos está pasando",
    "¿Sabes lo que pasa? Que esto no es verdad",
    "Mami, de tanto darle vueltas, dejó de girar",
    "La ilusión está herida, perdón que te diga",
    "Que no te decidas ta’ mal",
    "Lo que te cuento",
    "Es que no tengo tiempo pa’ una identidad",
    "Hecha de otro intento",
    "Ma’ costao’ tanto aliento que no queda na’",
    "Ya te lo he dado todo",
    "Empecé perdonando tus fracasos",
    "Te regalé todo mi compromiso",
    "Jugándome la vida por si acaso",
    "Enseñándote a no pedir permiso",
    "La protagonista no ha cumplido la misión",
    "Se ha desviado de la ruta",
    "Sigue buscando atención",
    "Las escaleras de su nombre no siguen la dirección",
    "Por la que daba su palabra y se jugaba el corazón",
    "Si mañana ya no somos nada",
    "Si mañana este mundo se acaba",
    "Dímelo cuando me pille volando",
    "To’ lo que prometimos en el aire flotando",
    "Vida sana pa’ que te quedaras",
    "Muchas ganas de verte la cara",
    "Sigo buscando, ese maldito mando",
    "Que ponga fin a to’ lo que nos está pasando",
    "No eras tú, la de la solicitud",
    "Apréndetela en YouTube",
    "Poquita actitud, te vale cualquier club",
    "Una más en la multitud-tud",
    "Tumba la casa que no hay testigos",
    "Nunca repasa si son amigos",
    "Bueno, ¿y si no qué más da?",
    "Luego te demuestro que nadie sabe na’",
    "Mi vida es un crossover capítulos nuevos",
    "Me sale “game over”, escucho los truenos",
    "Por to' la ciudad, ya sé que me estoy mojando, y bueno",
    "Otra tempora’ terminando, hasta luego",
    "La protagonista no ha cumplido la misión",
    "Se ha desviado de la ruta",
    "Sigue buscando atención",
    "Las escaleras de su nombre no siguen la dirección",
    "Por la que daba su palabra y se jugaba el corazón",
    "Si mañana ya no somos nada",
    "Si mañana este mundo se acaba",
    "Dímelo cuando me pille volando",
    "To’ lo que prometimos en el aire flotando",
    "Vida sana pa’ que te quedaras",
    "Muchas ganas de verte la cara",
    "Sigo buscando, ese maldito mando",
    "Que ponga fin a to’ lo que nos está pasando"
  ],
  "diva virtual": [
    "Me llegan alertas sobre la temperatura",
    "Pero solo me pasa en tu perfil",
    "Todo comenzó una tarde",
    "Parecía una diva virtual",
    "Le toqué el story y dio calambre",
    "Sentimouna' conexión astral",
    "Me llegaron un par de me gustas",
    "Nena, ¿cómo no me va a gustar?",
    "Notificaciones por toas’ partes",
    "Pasemos a la vida real",
    "Será verdad, que necesito curar",
    "Las cicatrices que mi cora no consigue cerrar",
    "Pero la casualidad, tiene más fuerza que el mal",
    "Y mi cabeza to’ las horas te quiere dedicar",
    "Atento a to’",
    "Voy de cara, no me arrepiento de na’",
    "Me di cuenta de que no quiero el control",
    "Ni la ruta, sin mapa es misión",
    "Yo deci-dónde, cuándo y qué tal",
    "Gástate un millón",
    "En valor sentimental",
    "Luego en el colchón",
    "Me toca a mí valorar",
    "Todo comenzó una tarde",
    "Parecía una diva virtual",
    "Le toqué el story y dio calambre",
    "Sentimouna' conexión astral",
    "Todo-todo-todo comenzó una tarde",
    "Parecía una diva virtual",
    "Le toqué el story y dio calambre",
    "Sentimouna' conexión astral",
    "Me llegaron un par de me gustas",
    "Nena, ¿cómo no me va a gustar?",
    "Notificaciones por toas’ partes",
    "Pasemos a la vida real",
    "No te conozco",
    "Pero los dos sabemos",
    "De qué palo va el otro",
    "Y qué palo si no hacemos",
    "Lo que nuestros circuitos ignoran",
    "Y mentes evitan",
    "Cuidado, seguro salpicas",
    "Minita digital de cuerpo analógico",
    "Carita pixelada con ojitos tóxicos",
    "Mira las stats, todo a level max",
    "Skin legendaria, no hay mejor avatar",
    "Y es que parece una peli dentroun' videojuego",
    "Ta' escribiendo al cel y le respondo luego",
    "Que estoy ocupao' buscando los hacks",
    "Que está utilizando pa’ tenerme AFK",
    "Si se desconecta vuelve la inseguridad",
    "Noto que me falta el aire, necesito respirar",
    "Formas parte de mi rutina, como un virus enganchá’",
    "Un troyano que me obliga a recordar",
    "Todo comenzó una tarde",
    "Parecía una diva virtual",
    "Le toqué el story y dio calambre",
    "Sentimouna' conexión astral",
    "Me llegaron un par de me gustas",
    "Nena, ¿cómo no me va a gustar?",
    "Notificaciones por toas’ partes",
    "Pasemos a la vida real"
  ],
  "lo siento": [
    "Bendiciones pa’ los que siguen aquí",
    "Conmigo hasta cuando no se disfruta",
    "Tengo tiempo reservao' pa’ mí y pa’ tos’",
    "No me di cuenta pero me olvidé de mil",
    "Y de millones que por su culpa me asustan",
    "Sin aliento, va otro intento pa’ los dos",
    "Lo siento pero me toca a mí",
    "Hacer to’ lo que a ella no le gusta",
    "Vivir las situaciones que no se llevar a cabo sin su olor",
    "De corazón me quiero arrepentir",
    "Aunque por suerte mi cabeza es más justa",
    "Felicidades por todas las ocasiones que fallaste a nuestro amor",
    "Y dime, tú por qué",
    "Te empeñaste en saber",
    "Qué pasaba cuando no podía ver",
    "Si tú misma me dijiste",
    "\"Cari, ¿por qué se mueren todas las relaciones el 23?\"",
    "Recuerdo que escribía",
    "La temperatura de la páginas fría",
    "Soñé, sin más miré",
    "Y tus ojos mentían una y otra vez",
    "Y ahora que me estás llamando",
    "Es el momento de que entiendas mamá",
    "Que lo siento pero me toca a mí",
    "Hacer to’ lo que a ella no le gusta",
    "Vivir las situaciones que no sé llevar a cabo sin su olor",
    "De corazón me quiero arrepentir",
    "Aunque por suerte en mi cabeza es más justa",
    "Felicidades por todas las ocasiones que fallaste a nuestro amor",
    "Lo siento pero me toca a mí",
    "Hacer to’ lo que a ella no le gusta",
    "Vivir las situaciones que no sé llevar a cabo sin su olor",
    "De corazón me quiero arrepentir",
    "Aunque por suerte mi cabeza es más justa",
    "Felicidades por todas las ocasiones que fallaste a nuestro amor",
    "Chulo, dile que ponga chulo",
    "Que sé que te gusta mi culo",
    "Vamos pa'l' zulo",
    "Me decía con la mirada",
    "Cinco estrellas en disimulo",
    "Y a la vez que yo me la creí",
    "No aceptaba saber la realidad por mí",
    "¿De qué vale confesar al mentir",
    "Si la puta verdad sigue dentro de ti?",
    "Que lo siento pero me toca a mí",
    "Hacer to’ lo que a ella no le gusta",
    "Vivir las situaciones que no sé llevar a cabo sin su olor",
    "De corazón me quiero arrepentir",
    "Aunque por suerte en mi cabeza es más justa",
    "Felicidades por todas las ocasiones que fallaste a nuestro amor",
    "To’ lo nuestro",
    "Por tu culpa se perdió"
  ],
  "rango superior": [
    "Me he despertao' con los reflejos del sistema solar",
    "En una cama con espejo por delante y detrás",
    "Ya he superao' to' mis complejos, no me via' preocupar",
    "Me fui a dormir como un conejo y no me gusta sudar",
    "Llevo tiempo acostumbrado a cuidarme regular",
    "Porfa no me hables de rutina, que la llevo fatal",
    "Nací con suerte o tuve ganas, según quién lo mira",
    "Si no consigo lo que quiero es porque lo tengo ya",
    "Chico, no pensaba, yo actué",
    "Sin tener ni la mitad de lo que tú, me la jugué",
    "Quise apuntar a lo más alto",
    "Y camarada, si gané",
    "Fue por clavar el lugar exacto",
    "Y el momento fetén",
    "¿Y por qué me siento vacío",
    "Emparejando-lores en tríos?",
    "Si aún tengo hambre",
    "Persigo el miedo",
    "Y en cada invierno muero de frío",
    "Y ten cuidado si te sientes el mejor",
    "Ten muy claro que tú eres clase alta",
    "Yo de rango superior",
    "Uf, qué barras se suelta el Ricky",
    "Pero no pasa nada",
    "Tiene doctrina, uh",
    "Si quiere doblar, tenemos tarifa, yeeeh",
    "Doblo las parties por palizón",
    "No me da una pali, me da la razón",
    "Algunos que piensan que tengo el don",
    "Otros que piensan que fue suerte",
    "Doble cara como un mapache",
    "A tu novia la amas, a mí me da lache",
    "No te imaginas qué desfase",
    "La noche anterior qué bien la pasé",
    "No me vuelva' a llamar la atención",
    "Mami, por ti me bebo otro ron",
    "Todo lo que me merecí está en la habitación",
    "Y tú hablando de mí como si hicieras algo",
    "Fumando olor a jazmín, me hice otro hidalgo",
    "Pasé de largo no me arrepentí",
    "Traicionaron a alguien no los seguí",
    "Escuchando Tiroteo like Marc Seguí",
    "Ricky si se aburre se come medio Spotify",
    "Y está tu nena tirándome el #HighFive",
    "Magus y Ricky lo han vuelto a hacer",
    "No se puede creer",
    "Pocos que confiaban ahora llevan marcas de cabeza a los pies, yeeh",
    "Tendría lo mismo si volviera a nacer, yeeh",
    "Salgo cargado de cada tienda que entro",
    "No sé si llevo Moncler",
    "Si la cami es Supreme",
    "Gucci o Prada",
    "No la voy a devolver",
    "Sa' quedao' en el hotel",
    "Mi nena quiere Dolce pa' combinarnos en mi Gabbana",
    "Me pongo en serio joder",
    "Mira en verdad no sé",
    "De alta gama",
    "¿Y por qué me siento vacío",
    "Emparejando-lores en tríos?",
    "Si aún tengo hambre",
    "Persigo el miedo",
    "Y en cada invierno muero de frío",
    "Y ten cuidado si te sientes el mejor",
    "Ten muy claro que tú eres clase alta",
    "Yo de rango superior",
    "¿Y por qué me siento vacío",
    "Emparejando-lores en tríos?",
    "Si aún tengo hambre",
    "Persigo el miedo",
    "Y en cada invierno muero de frío",
    "Y ten cuidado si te sientes el mejor",
    "Ten muy claro que tú eres clase alta",
    "Yo de rango superior"
  ],
  "hoa": [
    "Tenía olvidao tu nombre de hace tiempo",
    "Y me lo ha susurrao la brisa de este viento",
    "No localizo las palabras necesarias pa quedarme tranquilito",
    "Y noto que las llevo dentro",
    "Me gustaría pedirte perdón",
    "Pintarlo bonito durante el avión",
    "Gastar un ratito cerrando el hocico",
    "Y poner al Benito si hay otro apagón",
    "Ya está, ya se acabó",
    "Se ha muerto lo bonito que teníamos los dos",
    "Que sepas que siempre que me pregunten",
    "Inventaré cien mitos que se junten antes de tu puto adiós",
    "Mal acompañao, vale, pero nunca solo",
    "Me pillo tu helao, y eso que soy más de polo",
    "A veces miro al cielo, se me juntan las estrellas",
    "Y tu nombre se aparece como el 13 del Apolo",
    "Pensaba que era hambre, no que estaba aburrido",
    "La culpa me atormenta, me llueven sus ladridos",
    "Tenía miedo al enjambre por to lo florecío",
    "Recubiertas de alambre las flechas de Cupido",
    "Y ahora no puedo decirte",
    "Lo que dicen estas letras",
    "Ya no quiero desvestirte",
    "Solo quiero que me entiendas",
    "Y ahora no puedo decirte",
    "Lo que dicen estas letras",
    "Ya no quiero desvestirte",
    "Solo quiero que me entiendas",
    "Tenía olvidao tu nombre de hace tiempo",
    "Y me lo ha susurrao la brisa de este viento",
    "No localizo las palabras necesarias pa quedarme tranquilito",
    "Y noto que las llevo dentro",
    "Me gustaría pedirte perdón",
    "Pintarlo bonito durante el avión",
    "Gastar un ratito cerrando el hocico",
    "Y poner al Benito si hay otro apagón",
    "No está, ya se marchó",
    "Quizá se ha derretido con este puto calor",
    "Su voz me resonaba, pasando por las escalas",
    "Destacando en to las notas: Re, mi, fa, Sol, la, si, do",
    "Dicen que hay unos peces en el mar",
    "Me suena a dicho tonto pa que deje de llorar",
    "Si me ha quedao bien claro que no va a haber más",
    "Pero la noche no perdona y siempre te vuelvo a soñar",
    "Pensaba que era hambre, no que estaba aburrido",
    "La culpa me atormenta, me llueven sus ladridos",
    "Tenía miedo al enjambre por to lo florecío",
    "Recubiertas de alambre las flechas de Cupido",
    "Y ahora no puedo decirte",
    "Lo que dicen estas letras",
    "Ya no quiero desvestirte",
    "Solo quiero que me entiendas",
    "Y ahora no puedo decirte",
    "Lo que dicen estas letras",
    "Ya no quiero desvestirte",
    "Solo quiero que me entiendas"
  ],
  "prioridad": [
    "Me pasao al modo avión",
    "Me desinstalao' el reloj",
    "Me he quitao' las notis pa no ver tu ubicación cariño",
    "Me he mudao hasta el salón",
    "Me he puesto a mirar Tik Toks",
    "Me he dado cuenta de tus planes y es que no aparezco yo",
    "El desayuno en la camita",
    "Y pa' comer el caviar",
    "Venga tira que te invito a cenar",
    "Tú hazle fotitos a la luna",
    "Y yo a la estrella fugaz",
    "A la que pido toas las noches que me des prioridad",
    "El desayuno en la camita",
    "Y pa' comer el caviar",
    "Venga tira que te invito a cenar",
    "Tú hazle fotitos a la luna",
    "Y yo a la estrella fugaz",
    "A la que pido toas las noches que me des prioridad",
    "No he dormido en dos semanas",
    "No he subido las persianas",
    "Ya se me ha olvida'o que día de número es mañana",
    "Porque no he salido a la ventana",
    "Y no he tenido muchas ganas",
    "De escuchar excusas grandes, chicas ni medianas",
    "Y es que",
    "No he dormido en dos semanas",
    "No he subido las persianas",
    "Ya se me ha olvida'o que día de número es mañana",
    "Porque no he salido a la ventana",
    "Y no he tenido muchas ganas",
    "De escuchar excusas grandes, chicas ni medianas",
    "Y es que",
    "Sorry baby si molesto",
    "Te juro que sentirme to' pesa'o es lo que yo más detesto",
    "Siempre me la suda el resto",
    "Te he regala'o mis horas",
    "Y tú no me has da'o ni el segundo puesto",
    "Me pasa'o al modo avión",
    "Me desinstalao' reloj",
    "Me he quitao' las notis pa no ver tu ubicación cariño",
    "Me he muda'o hasta el salón",
    "Me he puesto a mirar Tik Toks",
    "Me he dado cuenta de tus planes y es que no aparezco yo",
    "El desayuno en la camita",
    "Y pa' comer el caviar",
    "Venga tira que te invito a cenar",
    "Tú hazle fotitos a la luna",
    "Y yo a la estrella fugaz",
    "A la que pido toas las noches que me des prioridad",
    "El desayuno en la camita",
    "Y pa' comer el caviar",
    "Venga tira que te invito a cenar",
    "Tú' hazle fotitos a la luna",
    "Y yo a la estrella fugaz",
    "A la que pido toas las noches que me des prioridad",
    "Que me des prioridad",
    "Que tampoco pido tanto, tan solo pido un poquito"
  ],
  "otra vida": [
    "El laberinto aprendí a solucionar",
    "De tu prisión escapar",
    "Para ver si era mejor avanzar",
    "En línea recta o volar mente directa",
    "Al final, me he dado cuenta de que no buscaba la salida",
    "Si mis ojitos ya no saben llorar",
    "No fue por no contestar",
    "A los 100 mensajes que iba a borrar",
    "Si te conectas, no salgo de tu secta",
    "Al final, me he dado cuenta, y no se me dan bien las despedidas",
    "Me valgo solo, pero tú qué bien me cuidas",
    "Tres intentos me he bastado superando tu partida",
    "No disfruto la bajada si no lucho la subida",
    "Cada uno por su lado, pero mi lado es mentira",
    "Se han terminao los regalitos y el pastel",
    "Ya no pregunto por jacuzzis cuando voy a un hotel",
    "Ya han despegao los avioncitos de papel",
    "Donde soñamos, escribimos y firmamos nuestra Luna de miel",
    "Se han consumío los cigarritos aftersex",
    "Echo de menos las cosquillas que guardaba tu piel",
    "Rompí tus cartas y tus foto' las quemé",
    "Pero el recuerdo de tus letras sigue siendo igual de cruel",
    "Me valgo solo, pero tú que bien me cuidas",
    "Tres intentos me he bastado superando tu partida",
    "No disfruto la bajada si no lucho la subida",
    "Cada uno por su lado, pero mi lado es mentira",
    "Se han terminao los regalitos y el pastel",
    "Ya no pregunto por jacuzzis cuando voy a un hotel",
    "Ya han despegao los avioncitos de papel",
    "Donde soñamos, escribimos y firmamos nuestra Luna de miel",
    "Se han consumío los cigarritos aftersex",
    "Echo de menos las cosquillas que guardaba tu piel",
    "Rompí tus cartas y tus foto' las quemé",
    "Pero el recuerdo de tus letras sigue siendo igual de cruel"
  ],
  "quema": [
    "Y ahora mirame como a los demás",
    "Verte con otro a mí me quema",
    "No quiero terminar",
    "Sintiendo que lo nuestro se olvida",
    "Gastando en Moschino, comprando en Chanel",
    "Las copas de vino fuera del hotel",
    "Pidiendo Chandon pregunta si él",
    "Te sigue queriendo o fue cosa de ayer",
    "Y es que no puedo parar",
    "De mi mente imaginar",
    "Lo que ya pudo pasar",
    "Entre tú y yo",
    "Gastando en Moschino, comprando Chanel",
    "Las copas de vino fuera del hotel",
    "Pidiendo Chandon pregunta si él",
    "Te sigue queriendo o fue cosa de ayer",
    "Y es que no puedo parar",
    "De mi mente imaginar",
    "Lo que ya pudo pasar",
    "Entre tú y yo",
    "Lo tenias to' y lo dejaste pasar",
    "Cara bonita pero el cora deja mucho que desear",
    "Le gusta el verde y los de 100",
    "Va de gatita del Edén",
    "Y si no miras se vuelve otro animal",
    "Le da igual",
    "Mami, me has gastado las 3 vidas",
    "Te has quedao' con to' las salidas",
    "Quemas la herida si tú no cuidas",
    "Que ego y orgullo por ti decidan",
    "Sorry, me quería quedar",
    "Pero ya no puedo más",
    "Houston, dale a DESPEGAR",
    "Y ahora estoy perdido en el espacio",
    "Buscando un sitio donde aterrizar",
    "Y no tengo miedo de chocar",
    "Contra asteroides o galaxias",
    "Porque no hay mayor desgracia",
    "Que sentir que no te sacia mi Mercurio",
    "Y ahora mirame como a los demás",
    "Verte con otro a mí me quema",
    "No quiero terminar",
    "Sintiendo que lo nuestro se olvida",
    "Sigo sintiendo ese frío si tú no estás",
    "Ahora es otro el que en tu cama suele estar",
    "Con el alma fría, sintiendo calor",
    "Estando con otro, pensando en tu olor",
    "Ahora no perdonas si pido perdón",
    "Todo lo nuestro lo pusiste en OFF",
    "Y esto es de los 2",
    "Mami esto es un caso aparte",
    "No digas que no",
    "Déjame ser como yo era antes",
    "Porque tú combinas mamá",
    "Ahora de lunes a viernes",
    "Creo que saldré un ratito pa' verte",
    "Pero si te molesta juro no convencerte",
    "Nuestro destino ahora lo dejo a la suerte",
    "Y quedate conmigo",
    "Quiero que seas mi camino",
    "Pongamo' a todos de testigo",
    "Que esto no es el final",
    "Gastando en Moschino, comprando Chanel",
    "Las copas de vino fuera del hotel",
    "Pidiendo Chandon pregunta si él",
    "Te sigue queriendo o fue cosa de ayer",
    "Y es que no puedo parar",
    "De mi mente imaginar",
    "Lo que ya pudo pasar",
    "Entre tú y yo",
    "Gastando en Moschino, comprando Chanel",
    "Las copas de vino fuera del hotel",
    "Pidiendo Chandon pregunta si él",
    "Te sigue queriendo o fue cosa de ayer",
    "Y es que no puedo parar",
    "De mi mente imaginar",
    "Lo que ya pudo pasar",
    "Entre tú y yo"
  ],
  "paqué": [
    "Han sido tantas veces viniéndome con lo mismo",
    "Maquillando tus palabras pa' alejarme del abismo",
    "Te los compro si tú me los vendes",
    "Hablo de los cuentos que forma tu mecanis-",
    "Mogollón de capítulos he abierto y me has cerrado",
    "Cien historias y aventuras",
    "Que te he escrito me has borrado",
    "Mil concursos de poesía por tu carita he ganado",
    "Pa' que acabes preguntándome porqué estoy tan rayado",
    "¿Pa qué quiero lo de antes?",
    "Así no puedo avanzar",
    "No me pintes de farsante solo porque sé actuar",
    "¿Pa' qué vas de interesante si me sé to' tu historial?",
    "No me pidas que elimine tus mensajes de Instagram",
    "¿Pa' qué quiero que levantes to' lo que vas a tirar?",
    "No me quedan más diamantes, deja ya de vacilar",
    "¿Pa' qué estudias a Descartes, si soy yo quien te va a echar?",
    "No me pidas que te cante si no me vas a escuchar",
    "¿Pa' qué te pones delante si te voy a dejar atrás?",
    "No me sirve un comandante que tiene miedo a luchar",
    "¿Pa' qué quiero verte un martes si el domingo ya no estás?",
    "No me pidas ver Mutantes si lo nuestro es Zombieland",
    "Mi especialidad, nunca ha sido la paciencia",
    "Siempre he sido de actuar por impulsos que no piensan",
    "En que puede salir mal, ignorando a mi conciencia",
    "Que ha entendido que mi nombre ya no sale en tus tendencias",
    "Me he aprendido a valorar, repasando tus patrones",
    "Me he estudiado las palabras que me dejaron lesiones",
    "¿Qué me mires o enfrentarme a los leones?",
    "De cabeza a los felinos, que tus ojos son cañones",
    "¿Pa qué quiero lo de antes?",
    "Así no puedo avanzar",
    "No me pintes de farsante solo porque sé actuar",
    "¿Pa' qué vas de interesante si me sé to' tu historial?",
    "No me pidas que elimine tus mensajes de Instagram",
    "¿Pa' qué quiero que levantes to' lo que vas a tirar?",
    "No me quedan más diamantes deja ya de vacilar",
    "¿Pa' qué estudias a Descartes, si soy yo quien te va a echar?",
    "No me pidas que te cante si no me vas a escuchar",
    "¿Pa' qué te pones delante si te voy a dejar atrás?",
    "No me sirve un comandante que tiene miedo a luchar",
    "¿Pa' qué quiero verte un martes si el domingo ya no estás?",
    "No me pidas ver Mutantes si lo nuestro es Zombieland",
    "Es que ¿pa' qué? ¿Pa' que?",
    "Si lo he intentado tantas veces que ya",
    "Ha perdido hasta la gracia",
    "Ya no encuentro motivos pa' seguir intentándolo tía",
    "Ya, ya me he cansao'",
    "Así que en fin, quédate con esto"
  ],
  "caliente": [
    "Una de pasta, de la que se come y no se gasta",
    "Me pido los Spaghettis gordos como rastas",
    "Basta, le he subido el brillo y no contrasta",
    "Tú eres mercadillo y yo dirijo la subasta",
    "Aplasta la mirada con la que me piensa",
    "No son amiguitas pero la fotito renta",
    "Mientan, le robé el zapato a Cenicienta",
    "No me quedan chicles, ¿y por qué me huele a menta?",
    "Sale con o sin pintura pa' la calle",
    "No le aguanto los ojitos sin que me desmaye",
    "Y dale, no soy de fijarme en los detalles",
    "No me eches la bronca niña pija no me ralles",
    "Vale, puede que mi pantalón estalle",
    "Si no me acompañas un ratito por el valle",
    "Y ale, ve con cuidadito pero dale",
    "Qué manos tan frías, prefiero que te la jales",
    "Si me sacas a bailar",
    "No te dejo respirar",
    "Si te acercas por detrás",
    "No hace falta decir más",
    "Ese culo me rellena tres menús",
    "Desayuno con tostadas y tus babitas untadas ¿Repelús?",
    "Achús, ¿te has puesto malita? Te digo: Salud",
    "Pero si eres religiosa, directamente: Jesús",
    "George Bush iba hace un ratito conmigo en el bus",
    "Me ha pedido una tirita pa' una herida llena pus",
    "No sé qué coño decía pero el muy cabrón sabía",
    "Que mi postre favorito era desplumarme en el mouse",
    "Siempre te pillo caliente",
    "No sé por qué tantas ganas niña últimamente",
    "No me molesta la gente",
    "He hecho cosas raras, que miren se me hace frecuente",
    "Pido que no seas paciente",
    "Que si me ves muy salvaje, tú seas mi serpiente",
    "Siento tu cora' latente",
    "Tú solo sigue mi ritmo y aprieta los dientes",
    "Mami, tú no te preocupes, que esto no echa humo",
    "Vale, que mis amiguitos fumen, pero yo no fumo",
    "Si en las fiestas las botellas que me bebo son de zumo",
    "Vete ya a dormir tranquila y no preguntes si consumo",
    "Si me sacas a bailar",
    "No te dejo respirar",
    "Si te acercas por detrás",
    "No hace falta decir más",
    "Yo me lo plancho, si me necesitas soy tu gancho",
    "Ma toca'o la lotería ladro como pancho",
    "Un rancho, te he comprado maldita así que ponme la boquita",
    "O si no quita que te juro que te mancho",
    "¿Cómo? ¿Que alguien se lo ha dicho a tu maromo?",
    "Chico ¿No sabías que coleccionaba cromos?",
    "Va si te pregunta dile que soy Juan Arroyo",
    "No lo guiso y me lo como, me la pido y me la follo",
    "No contesta ¿La llamo o me cargo la fiesta?",
    "¿Cuánto cuesta? La tarifa que incluye respuesta",
    "Qué modesta, no somos na' y ya me detesta",
    "Sumo y resta, va, pide la cuenta que voy a echar la siesta"
  ],
  "noche": [
    "M'han dicho que estás buscando y que no puedes encontrar",
    "Al bicho que está gritando y que solo ve oscuridad",
    "Dando vueltas con el coche solo en medio de la noche",
    "Recordando como hacíamos sonar",
    "Que no me vienen bien pero tampoco mal tus besos",
    "Y entérate, si te llevo al Edén, parezco un Satanás travieso",
    "Tú en la cárcel y yo siempre el preso",
    "La gatita y el puto sabueso",
    "Siempre me dices lo mismo, luego solo hay risas, una copa y mucho sexo",
    "Que a mí no me hacen bien pero tampoco mal tus besos",
    "Espérate, no puedo ir al Edén, hace mucho que no me confieso",
    "Y tú cedas si te quedas preso",
    "Pégate a mi lado, tengo un hueso",
    "Siempre me dices lo mismo, luego solo hay risas, una copa y mucho sexo",
    "Conozco mis limitación, pero no sabes cómo es (sabes cómo es)",
    "De difícil seguir los patrones si, mami, no te dejas ver (no te dejas ver)",
    "No lo quiero aprender, te juro la moto no te voy a vender",
    "Y eso que estoy buscando plata, que iba a hacerme un piti",
    "Pero no me queda papel",
    "Si te digo que ya te he olvidado, creo que te miento",
    "Yo me alejé de ti, pero eso sé que no lo intento",
    "Y es que siento que me estoy equivocado",
    "Cuando me acerco hacia ti porque te extraño",
    "A ti no te cunde y a mí no me renta",
    "Que salte tu culo en los stories de mi cuenta",
    "Deja de pedirme que te llame Cenicienta",
    "Ya perdí un zapato y yo tengo tu vestimenta",
    "A mí no te cunde y a ti no me renta",
    "Que me entere que has puesto tú móvil a la venta",
    "Si me lo pediste a cuatro pati-, 360",
    "Pa vernos chingando en 4K a cámara lenta (ey, ey)",
    "M'han dicho que estás buscando y que no puedes encontrar",
    "Al bicho que está gritando y que solo ve oscuridad",
    "Dando vueltas con el coche solo en medio de la noche",
    "Recordando como hacíamos sonar",
    "Que no me vienen bien pero tampoco mal tus besos",
    "Y entérate, si te llevo al Edén, parezco un Satanás travieso",
    "Tú en la cárcel y yo siempre el preso",
    "La gatita y el puto sabueso",
    "Siempre me dices lo mismo, luego solo hay risas, una copa y mucho sexo",
    "Que a mí no me hacen bien pero tampoco mal tus besos",
    "Espérate, no puedo ir al Edén, hace mucho que no me confieso",
    "Y tú cedas si te quedas preso",
    "Pégate a mi lado, tengo un hueso",
    "Siempre me dices lo mismo, luego solo hay risas, una copa y mucho sexo"
  ],
  "badabadún": [
    "Badabadún, badún, badún badún badero",
    "Hace tiempo era un niñato que quería tener dinero",
    "Tranquilo, sosegao', muy calmadito y relajao'",
    "No me saques a la pizarra que me pillas to' empalmao'",
    "Acaba de empezar el viernes ¿cómo voy a estar alterao'?",
    "Y aquí estoy, to' preocupao'",
    "Siempre recomiendan que escuche y aprenda",
    "Pero le he copiao' al de mi lao' la agenda",
    "La profe me diga que no me entretenga",
    "Pero la chivata quiere que la atienda",
    "Mañana mi madre me pide las notas",
    "Si se las entrego me parte la boca",
    "No puedo mentirle, siempre me lo nota",
    "Le pondré la cara del gato con botas",
    "He suspendido gramática",
    "Chándal pa' educación física",
    "Sin cartulina pa' plástica",
    "Contigo siento la química",
    "No tengo flauta pa' música",
    "Ni regla pa' matemáticas",
    "Voy a comerme a la gótica",
    "Que en reli toca película",
    "Ha sonado la campana",
    "Tiro pa'l recreo buscando a tu hermana",
    "Aunque no esté a mi alcance y me saque tres años",
    "Su carita es lo que me hace la semana",
    "Apostando canicas y tazos mañana",
    "Me pillo un zumito de piña o manzana",
    "Que los de segundo me han quitao' el bocata",
    "Y se lo están comiendo escuchando al tangana",
    "Tumbaito', apaciguao', muy calentito y despejao'",
    "Te cuento qué hago por tarde, que me pillas to' empanao'",
    "Como la lío bastante en casa al comedor me han apuntao'",
    "Siempre ponen purés y sopas y me las como obligao'",
    "Ya desde fuera me huele a nevera",
    "Que tiene más mierda que la papelera",
    "Mucho cuidadito con la cocinera",
    "Si te dejas algo te saca las tijeras",
    "Hoy toca filete en no muy buen estado",
    "Y patatas mojadas del año pasado",
    "Toma tu bebida, Fanta de hacendado",
    "Y si llegas al postre, yogurt caducado",
    "He suspendido gramática",
    "Chándal pa' educación física",
    "Sin cartulina pa' plástica",
    "Contigo siento la química",
    "No tengo flauta pa' música",
    "Ni regla pa' matemáticas",
    "Voy a comerme a la gótica",
    "Que en reli toca película",
    "Badabadún, badún, badún badún badero",
    "Pa' clases particulares con la pija de tercero",
    "Badabadún, badún, badún badún badero",
    "Me ha gustado tanto el curso, voy a repetirlo entero"
  ],
  "y más allá": [
    "Una máquina del tiempo mi cabeza ha fabricado",
    "Porque cuando estoy contento, parezco superdotado",
    "Nunca he sido muy de inventos, quiero dejar comprobado",
    "Si el futuro siguen siendo mis errores del pasado",
    "Y es que pa volar debo acelerar",
    "Y aunque esto sea cosa mía, no consigo encontrar",
    "El combustible, la gasolina",
    "Que me aleje poco a poco del más que repetido planeta Tierra",
    "Y si te apetece, hasta el infinito y más allá",
    "Hasta el infinito y más allá",
    "Como diría mi gran amigo Buzz Lightyear",
    "Hasta el infinito y más allá",
    "Y si el vaquero me abandona algún día",
    "Eso será otra película",
    "Trae tu tazón, yo pongo los cereales",
    "Una rata cocinera me va dando las señales",
    "Coge mi Copa Pistón, tómala como un detalle",
    "Igual que el tatu que encontró McQueen corriendo por el valle",
    "Me revienta que me juzgues por mis vestimentas",
    "Y que luego pidas zapatitos, Cenicienta",
    "Mejor seme sincera y, porfa, haz caso ya a ese niño de madera",
    "Que repite el mismo cuento desde los años 40",
    "¿Es que no te das cuenta?",
    "Tan solo te ha pedido que no mientas",
    "Hasta el infinito y más allá",
    "Como dirían Peter Pan y Campanilla",
    "Hasta el infinito y más allá",
    "Y si prefieres ser una niña perdida",
    "Me quedo en El país de Nunca Jamás",
    "Nunca me he sentido bien dando consejos",
    "Alicia llegó tarde por seguir el de un conejo",
    "Refléjate; si eres Blancanieves, yo tu espejo",
    "Y que Ariel se encargue de los siete enanos y el cangrejo",
    "Si tú has llegao primera, no me importa ir el segundo",
    "Hoy te veo muy bien, mi dama, ¿puedo ser tu vagabundo?",
    "Sería el responsable del mejor circo del mundo",
    "Conociendo a tus payasos, ¿a quién le hace falta Dumbo?",
    "To-ran-ta-ta, to-ra, ta-ta-ra-ta",
    "Hasta el infinito y mas allá",
    "Hasta el infinito y más allá",
    "Soy un cachorro, y tú Cruella de Vil",
    "Debí hacer más caso a Lilo y Stitch",
    "No encuentro la alfombra que me dio Aladdín",
    "Y ya no me hace caso, creo que está con Jasmín"
  ],
  "casa": [
    "Porfa, cinco minutos más",
    "Te juro por snoopy que me voy a levantar",
    "Bingo! Se la he vuelto a colar",
    "Menuda nochecita to viciao al mario kart",
    "No sé si me toca chandal o uniforme",
    "Con tantas cosas dentro de la mochila está deforme",
    "La abuela dice que con un 5 no me conforme",
    "Pero esa profesora a mí me tiene un asco enorme",
    "Me levanto, me ducho, doraemon escucho",
    "Me pongo bien las gafas que clara me ve feucho",
    "Preparo el estuche",
    "Tú estás muy flacucho",
    "Te veo luego mami, recuerda: Te quiero mucho",
    "Coche, piso y la luz pagar",
    "No eran mis problemas cuando estaba con papa",
    "Anoche quiso un ratito hablar",
    "Pero estaba liado siendo un puto subnormal",
    "Puede bajarse ricky a jugar?",
    "Lo pillas estudiando y ahora le voy a preguntar",
    "Donde se ha quedado el pictochat?",
    "Me da mucha pereza responder a los whatsapps",
    "Por fin papi llega a casa del trabajo",
    "Lo noto reventado, con el animo muy bajo",
    "Se pone a hacer la cena, le ayudo pelando un ajo",
    "Y me dice ten cuidadito mi pequeño renacuajo",
    "No hay cosa más buena que meterse en vena",
    "Filete empanado durante la cena",
    "De fondo que suena? Tol ruido y sirenas",
    "Mejor escuchar hormiguero en antena",
    "Coche, piso y la luz pagar",
    "No eran mis problemas cuando estaba con mama",
    "Anoche quiso un ratito hablar",
    "Pero estaba ocupado siendo un puto subnormal",
    "No me quiso la play comprar",
    "Y de no ser por eso no sabria valorar",
    "Lo que visto, y lo que es ganar",
    "Soy alguien de provecho, gracias a papa y mama"
  ],
  "gourmet": [
    "A veces lloro sentadito en mi jet",
    "Hoy quiero dormir a tu lado en nuestro humilde chalet",
    "Ya me he operado de la vista, tengo cita en el dentista",
    "Y me he hecho hasta terraplanista pa' no verte caer",
    "Cómo le queda el bikini a mi sirena",
    "Mientras me como un bikini aquí en la arena",
    "Cromos Repes de Panini, una docena",
    "En el fondo de bikini no hay problemas",
    "Ya ha pasado casi un año de ese verano",
    "Eras la excusa de mis vacaciones",
    "Debi darte más tiempo con to' lo que gano",
    "Me he dado cuenta ahora de todo lo que me pones",
    "Te dije que siempre que tú vas yo vengo",
    "Y ahora me he dao' cuenta de que esa mierda es un cuento",
    "Quería que gastaras toda la pasta que tengo",
    "Pero mi puta fortuna no puede pagar tu tiempo",
    "De vez en cuando me considero chef",
    "Estás tan buena que tu culo está en la carta gourmet",
    "Porque eres la protagonista, la primera de la lista",
    "Que por ti me hago taxista aunque no tenga el carnet",
    "A veces lloro sentadito en mi jet",
    "Hoy quiero dormir a tu lado en nuestro humilde chalet",
    "Ya me he operado de la vista y tengo cita en el dentista",
    "Me he hecho hasta terraplanista pa' no verte caer",
    "Yo en mí lambo y tú en tu mini, que bien suena",
    "Te dejo llamarme nini, que condena",
    "Yo soy Donald y tu Minnie, ay qué pena",
    "Te miro como LingÜini a su morena",
    "Dejas mejor sabor de boca que la Coca-Cola",
    "Está mejor sin el dolor de imaginarte sola",
    "Que lo mejor de este calor sea dejarte en bolas",
    "Quizá mejor será que no sepas to' lo que molas",
    "Contigo el Sol, sale toda la semana",
    "No recordaba lo que era la lluvia en la mañana",
    "Pero desde hace un tiempo la tormenta es mi tormento",
    "Y me atormenta to' este viento que me obliga a estar en cama",
    "De vez en cuando me considero chef",
    "Estás tan buena que tu culo está en la carta gourmet",
    "Porque eres la protagonista, la primera de la lista",
    "Que por ti me hago taxista aunque no tenga el carnet",
    "A veces lloro sentadito en mi jet",
    "Hoy quiero dormir a tu lado en nuestro humilde chalet",
    "Ya me he operado de la vista y tengo cita en el dentista",
    "Me he hecho hasta terraplanista pa' no verte caer",
    "Pa' no verte caer",
    "Pero si te caes",
    "Que yo te cojo"
  ],
  "en verdad": [
    "Ya hace tiempo que solo sé que no quiero estar",
    "He intentado confundirme con mil cosas más",
    "Siempre que estoy a cien tú me puedes frenar",
    "Y es verdad que nunca he sabido ver una oportunidad",
    "Pa' cerrar la puta boca e intentarte besar",
    "Cuando todo está bien siempre me vienes mal (siempre me vienes mal)",
    "La verdad es que he pasado por mucho para no avisar",
    "A mi corazón cuando pierdo la cabeza",
    "Voy montado en un tren que no llega al final",
    "Okay, quiero soltar una historia de las de películas, con cenas y con noria",
    "Donde no existen protagonistas, ya que aquí la única trama son las risas",
    "Que consigo mantener en mi memoria",
    "Han pasado tantos años, que no, que estoy de coña",
    "Prometo que esta no va a ser tan ñoña",
    "Si casi no nos conocemos",
    "Solo sé que te respondí a un mensaje y tiré pa'l garage con llaves",
    "Para verte y volver, puede que algo beber, no busco otro placer",
    "Trato de conocer si sabes responder, si se te da tan bien",
    "Hacerlo como lo haces por Direct",
    "Y es que, yo no logro entender, saber o comprender",
    "El motivo por el que se te da tan bien",
    "Pero es que desquiciarme lo haces fetén (volverme loco se te da bien)",
    "No quiero líos, no quiero un buen argumento",
    "Me basta verte bien para que pueda estar contento",
    "Y pa' toas' las mariposas, lilas, azules y rosas me tragao' un insecticida pa' que veas lo intento",
    "Todavía recuerdo aquel día sin haberte visto ya te conocía",
    "O al menos sabía lo que sentiría al pasar un ratito con esa peazo', tía",
    "Ya hace tiempo que solo sé que no puedo estar",
    "He intentado confundirme con mil locas más",
    "Siempre que estoy a cien tú me quieres frenar (y yo no sé si parar)",
    "Y es verdad que nunca he sabido ver una oportunidad",
    "Pa' cerrar la puta boca e intentarte besar",
    "Cuando todo está bien siempre me vienes mal",
    "Siempre me vienes mal, siempre me vienes mal",
    "Siempre me vienes, siempre me vienes, siempre me",
    "Si te soy sincero, me vienes fatal"
  ],
  "por ti": [
    "Alguien me ha preguntado tú y yo",
    "¿Qué es lo que somos?",
    "Y yo pa' esas preguntas",
    "Mucho tiempo me tomo",
    "Aunque te llame nena",
    "Para mí eres de plomo",
    "Sé que no es tu problema",
    "Tranqui, yo me lo como",
    "No me cuesta imaginar",
    "Llevarte de la cintura",
    "Me la suda el que dirán",
    "Pero no sé si estás segura",
    "No sé si quiero salir",
    "Contigo de esta tortura",
    "Si te he estao' mirando",
    "Y to' los días pensando en cada una de tus posturas",
    "A ciencia cierta",
    "Nunca sé lo que decir",
    "Cuando creía tenerlo claro",
    "Una vez más me arrepentí",
    "¿De que nos sirve seguir reservando hoteles en Madrid?",
    "Si cada vez que te miro a los ojos",
    "Sé que estás por mí y yo estoy por ti",
    "Por no romperlo todo",
    "Ahora estamos así",
    "Por no joderlo",
    "Nunca llegamos al fin",
    "Sumando todas las chorradas",
    "Que te dije y me dijiste",
    "Por no comernos",
    "Esa duda sigue ahí",
    "Por no beber",
    "Más Coca-Cola y Bacardí",
    "Pornografía es lo que imagino",
    "Que estoy haciendo contigo",
    "La canción de Marc Seguí",
    "Aunque me aten cadenas",
    "Hechas de hierro y plomo",
    "Sé que esta es mi condena",
    "Tranqui, yo me la como",
    "No puedo estar despierto",
    "Me quiero dormir",
    "A ver si sueño que tras la tormenta",
    "El Sol vuelve a salir",
    "¿De qué me sirven dos entradas",
    "Para Disneyland París?",
    "Si cada vez que te miro a los ojos",
    "Sé que estás por mí y yo estoy por ti",
    "Que estás por mí y yo estoy por ti"
  ],
  "mi habitación": [
    "Han pasado tantas cosas desde el día en que te fuiste",
    "Me han bajado los me gusta porque ya nadie me viste",
    "Se me han quitado las ganas de contarle a alguien mis chistes",
    "Y se me ha cerra'o la herida del labio que me mordiste",
    "Confiaba en un señuelo pero tú nunca volviste",
    "Se me han antoja'o los platos cinco estrella que me hiciste",
    "Ya he quemado todos los filtros que algún día me descubriste",
    "Y cuando salgo sonriendo en las historias estoy triste",
    "Adicción a su corazón traducido en una maldición",
    "Que es un calentón, poco a poco quemando el colchón",
    "Con una oración que no necesita religión, porque ahí estoy yo",
    "Pensando en ti en mi habitación",
    "Te has olvida'o tu olor pegado a mi edredón",
    "Si pongo Netflix tienes que iniciar sesión",
    "Le pido a Alexa porfa apaga el proyector, para estar mejor",
    "Y empieza a sonar nuestra canción",
    "Que importa un piso, una cabaña o una mansión",
    "Contigo me había tocado el Euromillón",
    "Y aunque no fume sigo saliendo al balcón",
    "Llueva o haga Sol, por si miras que ahí esté yo",
    "Y si no estoy, no sé a dónde voy",
    "Nadie más que tú sabe quién soy",
    "Si pillo un convoy que vuelva mañana y salga hoy",
    "Todo te lo doy como le dijo Gabriella a Troy",
    "Me confundiste, preguntaba y te reíste",
    "Si no quieres responderme en cero coma te desvistes",
    "Conocías mi punto débil y enseguida te luciste",
    "Yo era el mago, pero fuiste tú quien desapareciste",
    "Adicción a su corazón traducido en una maldición",
    "Que es un calentón, poco a poco quemando el colchón",
    "Con una oración que no necesita religión, porque ahí estoy yo",
    "Pensando en ti en mi habitación",
    "Te has olvida'o tu olor pegado a mi edredón",
    "Si pongo Netflix tienes que iniciar sesión",
    "Le pido a Alexa porfa apaga el proyector, para estar mejor",
    "Y empieza a sonar nuestra canción",
    "Que importa un piso, una cabaña o una mansión",
    "Contigo me había tocado el Euromillón",
    "Y aunque no fume sigo saliendo al balcón",
    "Llueva o haga Sol, por si miras que ahí esté yo"
  ],
  "era": [
    "Una vida sin pensar",
    "Que será lo que vendrá",
    "Con el próximo amanecer",
    "No me quiero preocupar",
    "De la vida los demás",
    "Si ni con la mía sé que hacer",
    "De bueno volví a pecar",
    "Dando una oportunidad",
    "A lo que evitaba prometer",
    "Y ahora no puedo llorar",
    "Sin que ni una lágrima",
    "Me grité lo que te dije ayer",
    "Te necesito olvidar",
    "Cada día me dueles más",
    "Soy consciente de que no estás bien",
    "Mi cabeza viene y va",
    "Navegando por un mar",
    "En el que se ahoga mi querer",
    "Quedan restos de algo más",
    "Con ideas pa divagar",
    "Varias horas antes de caer",
    "En la cama una vez más",
    "Tratando de conciliar",
    "Un insomnio que siempre está fiel",
    "Ey tío, supongo que estás a tus cosas, nada",
    "Es que, me he puesto a mirar conversaciones antiguas y",
    "Joder, es que te echo de menos, es que creo que te necesito tío",
    "Si escuchas esto, llámame, dime algo o borralo no importa",
    "Fui yo quien quiso arriesgar",
    "Hacia el futuro mirar",
    "Y asumí que tu estarías en él",
    "Nunca me obligue a cambiar",
    "En tu mano siempre esta",
    "Llevar tu vida como un rehén",
    "Yo no me puedo culpar",
    "De haber querido ocultar",
    "Los problemas de una vida cruel",
    "Si escondiendo la verdad",
    "Era posible lograr",
    "Que lo nuestro mundo fuera el edén",
    "No puedes mirar atrás",
    "Ya que prendes ese gas",
    "Quemaduras y pones la piel",
    "La palabra \"reparar\"",
    "Ya no se puede arreglar",
    "El manual son cenizas de ayer",
    "Echar de menos es más",
    "Falta grave y personal",
    "Si en verdad te echo en falta otra vez",
    "Me van a diagnosticar",
    "Corazón y cabeza ¿estáis bien?"
  ],
  "u banned": [
    "Twitch, esta pa' ti, disfruta",
    "To' los días abrimos directo",
    "Pensando en la risa, la pasta y los besos",
    "Y habrá quien te diga, no lo hago por eso",
    "Me río en tu cara no me seas travieso",
    "Oye que a mí no me pillas de nuevas",
    "Llevo mucho tiempo viendo las estrellas",
    "Me cansé de YouTube, el insta pa' ella",
    "No voy al colegio, yo fundé la escuela",
    "Perdona si pica, que vista de oro",
    "Te cuento un secreto, en verdad todo escobre",
    "Si sabes llevarlo parece un tesoro",
    "Pero si te pasas baneado por pobre",
    "De repente me llega un escrito",
    "De parte de quien me suelta el dinerito",
    "Diciendo que mida mejor mis palabras",
    "Que vaya pendiente y tenga cuidadito",
    "Venga ya, a mi edad voy a tener que controlar",
    "Las coñas que tengo con to' mis colegas",
    "De aquí a una semana esta censura'",
    "Cavando palabras sin tener contexto",
    "Pa' que el colectivo se duerma contento",
    "Cerrando canales da igual el pretexto",
    "Y si quieres quejarte, mensaje directo",
    "Ja ja ja, que va te imaginas que te han baneado",
    "Pilla dormidina o ponte a mandar tickets",
    "Que de vez en cuando vienen bien los chistes en las oficinas",
    "Me pongo a mirar notificaciones",
    "Buscando en Andorra alquiler de mansiones",
    "Cartita de Twitch, que no tire beef",
    "Que deje un rato de tocar los cojones",
    "No tuve culpa de nacer humano",
    "No te hago gracia te doy la mano",
    "Vale que a veces me pase un poquito",
    "Pero le metisteis tres meses a mi hermano",
    "Vaya temita del conejo malo",
    "Jugando diez horas es como un regalo",
    "No tengas huevos a ponerla en directo",
    "Si no quieres bulla con sus abogados",
    "Hace algunos años lo dejé bien claro",
    "El rojo de YouTube no puede al morado",
    "Pero detallitos como las canciones",
    "Han hecho que muchos ya se hayan mudado",
    "Barra comercial, barra comercial, 180 es",
    "Si no quieres ver anuncios dame el prime y callate",
    "Que más da, la verdad, que ponga publicidad",
    "Si lo que me llevo varía en función de lo bien",
    "Que me lleve con el mandamás",
    "Bla bla bla (sh)"
  ],
  "4k/mes": [
    "Me voy a levantar que hora es ya me la suda",
    "Miro por la ventana y hasta el Sol me saluda",
    "Me ducho porque la noche de ayer fue dura",
    "Mientras un afilia'o me hace la manicura",
    "Me apetece comprar cualquier tontería",
    "Se ha pasa'o Black Friday ya me jodería",
    "Recibo una llamada de mi agente y me vuelvo a la cama",
    "Por lo visto hermanito me ha toca'o la lotería",
    "Y sin jugarla viene pagada por una marca",
    "Que quieren ver sus joyas en mis yates y en mis barcas",
    "Se ajusta la tarifa, se ajusta las condiciones",
    "Y en Tarifa este verano yo me toco los cojones",
    "¿Pero quién eres?",
    "Y yo que sé",
    "¿Tú te crees alguien?",
    "Bro, ¿no me ves?",
    "Cierra la boca",
    "¿Y esa casita?",
    "Ya me la sé",
    "¿Bueno tú crees?",
    "Me lo han contado",
    "Anda, que bien",
    "Bro me das asco",
    "Si tan mal te caigo yo me voy pa’ Andorra",
    "Que aquí ma’ cogio’ mucha confianza la muy zorra",
    "No hablo de tu madre, de tu hermana, de tu novia",
    "Hacienda se aprovecha mucho más que to’ esa escoria",
    "Miro directs aburrido viendo notificaciones",
    "Veo insultos, muchas críticas y muchos seguidores",
    "Justifican que mi vida no tiene ningún sentido",
    "Al mismo tiempo que la Esposito me mete en sus mejores",
    "Paso a Twitter",
    "Tanto friki parece un combite",
    "Tos llorando por la nueva season del Fortnite",
    "Mezclao’ con intensitas mentalmente irás a pique",
    "Cuya meta en esta vida es que les de like Aaron Piper",
    "No me vas a echar la culpa de to’ lo que he currao’",
    "Pa’ estar aquí (yo estoy de chill)",
    "Y si no te parece un trabajo corre",
    "Pa’ tu casa a abrir stream (que tengas suerte)",
    "No tiene sentido que me saque",
    "Más que otro ya sea médico, bombero, policía o PabloMotos",
    "Pero luego bien que pagas ser el socio de tu equipo",
    "Pa’ que Messi siga siendo el millonario favorito",
    "No compares, a mi no me pagan por mis actos",
    "Mis horas y jornadas no salen en un extracto",
    "Las cobró porque la peñita que si las disfruta",
    "Llenaría 4500 salones de acto",
    "Me llaman de la tele pa’ grabar una entrevista",
    "En el buzón tengo solicitud de pa’ cubrir revistas",
    "Es curioso que hace na’ éramos los malos de la pista",
    "Y ahora que somos noticia los primeros de la lista",
    "Humildad, gran palabra aunque no la sabéis usar",
    "Ser humilde no consiste en tu fortuna regalar",
    "Solo necesitas tener claro, bro diferenciar",
    "Entre liarla en internet y ser un capullo integral",
    "No me gusta dar lecciones",
    "Tiene negro los cojones",
    "Ya hace tiempo que no soy el de parodiando canciones",
    "He crecido y madurado",
    "Con colegas a mi lado",
    "Y si creías que he terminado",
    "Este cabrón solo ha empezado"
  ],
  "mamisabesqno": [
    "Han pasado tantas cosas desde el día en que te fuiste",
    "Me han bajado los me gusta porque ya nadie me viste",
    "Se me han quitado las ganas de contarle a alguien mis chistes",
    "Y se me ha cerra'o la herida del labio que me mordiste",
    "Confiaba en un señuelo pero tú nunca volviste",
    "Se me han antoja'o los platos cinco estrella que me hiciste",
    "Ya he quemado todos los filtros que algún día me descubriste",
    "Y cuando salgo sonriendo en las historias estoy triste",
    "Adicción a su corazón traducido en una maldición",
    "Que es un calentón, poco a poco quemando el colchón",
    "Con una oración que no necesita religión, porque ahí estoy yo",
    "Pensando en ti en mi habitación",
    "Te has olvida'o tu olor pegado a mi edredón",
    "Si pongo Netflix tienes que iniciar sesión",
    "Le pido a Alexa porfa apaga el proyector, para estar mejor",
    "Y empieza a sonar nuestra canción",
    "Que importa un piso, una cabaña o una mansión",
    "Contigo me había tocado el Euromillón",
    "Y aunque no fume sigo saliendo al balcón",
    "Llueva o haga Sol, por si miras que ahí esté yo",
    "Y si no estoy, no sé a dónde voy",
    "Nadie más que tú sabe quién soy",
    "Si pillo un convoy que vuelva mañana y salga hoy",
    "Todo te lo doy como le dijo Gabriella a Troy",
    "Me confundiste, preguntaba y te reíste",
    "Si no quieres responderme en cero coma te desvistes",
    "Conocías mi punto débil y enseguida te luciste",
    "Yo era el mago, pero fuiste tú quien desapareciste",
    "Adicción a su corazón traducido en una maldición",
    "Que es un calentón, poco a poco quemando el colchón",
    "Con una oración que no necesita religión, porque ahí estoy yo",
    "Pensando en ti en mi habitación",
    "Te has olvida'o tu olor pegado a mi edredón",
    "Si pongo Netflix tienes que iniciar sesión",
    "Le pido a Alexa porfa apaga el proyector, para estar mejor",
    "Y empieza a sonar nuestra canción",
    "Que importa un piso, una cabaña o una mansión",
    "Contigo me había tocado el Euromillón",
    "Y aunque no fume sigo saliendo al balcón",
    "Llueva o haga Sol, por si miras que ahí esté yo"
  ],
  "navimal": [
    "Ya llega el fresquito",
    "Ya llega la Navidad",
    "Calcetines y pijamas",
    "De pelito ve a comprar",
    "No es que haga más frío",
    "No te vas a congelar",
    "Pero luego la factura",
    "No la paga Baltasar",
    "Pilla una mantita",
    "Y pon el móvil a cargar",
    "Pa' subir cuarenta stories",
    "Cuando nieve en tu ciudad",
    "Si vives en Murcia",
    "Igual no puedes vacilar",
    "Pero tendrás batería",
    "Para jugar al Clash Royale",
    "Santa Claus ya viene (ya está aquí)",
    "La play 5 tiene (por fin)",
    "Si no le conviene",
    "Va a traerte un",
    "Pedazo de abrigo",
    "Que no habías pedido",
    "Si tas' portao' mal",
    "¿Tu que te habías creído?",
    "Busca algún amigo",
    "Que haya suspendido",
    "Y así no se pasa",
    "Tan lento el castigo (oh oh oh)",
    "Joder, por fin",
    "Podemos ser muchos en casa",
    "Ya no hay tantas restricciones",
    "Pero el Covid no se pasa",
    "Yo echo un cable en la cocina",
    "Preparando bien la masa",
    "Mientras intento explicarle a",
    "Mi madre un meme de WhatsApp",
    "He escuchado en las noticias",
    "Que va a haber un apagón",
    "Tan solo espero que el Biza",
    "Saque una última sesión (Paulo)",
    "Mientras queden polvorones",
    "Mantecados y turrón",
    "Me la suda un poco lo que diga",
    "Los reyes ya vienen (ya han llegao')",
    "La nintendo tienen (pa' mi)",
    "Si no les conviene",
    "Te traerán un pe",
    "Si tan' quedao' cinco",
    "¿De qué vas listillo?",
    "Ahora por pardillo",
    "Te vas pa'l' pasillo",
    "Con to' la resaca",
    "Y nuevos calzoncillos (ho ho ho)",
    "Deja el odio echao' pa' un lado",
    "Que la Navidad es pa' estar feliz",
    "Que la Navidad es pa' estar feliz",
    "Que la Navidad es pa' estar feliz",
    "Y si no te traen regalos",
    "Pues no pasa na'",
    "Yo estaré en Twitch",
    "Pues no pasa na'",
    "Yo estaré en Twitch",
    "Y si no te gusta esta pa' ti"
  ],
  "quelamamen": [
    "¡Hey! Buenos días a la cinco de la tarde",
    "Soy hombre de costumbres y mi agenda está que arde",
    "Me miro los bolsillos con carita de cobarde",
    "Porque un compi me dio cositas pa' que se las guarde (no)",
    "Si preguntan, ese no era yo",
    "Si me buscan: Desapareció",
    "Me chamuscan con la vibración",
    "Deja de mandar gitanos te lo pido",
    "Por favor, que alguien me explique cómo funciona internet",
    "Que aún me sabe todo a Ron Cacique",
    "Y es que he intentado decir algo en un lugar llamado Twitter",
    "Sin que a nadie le salpique",
    "Buscando a alguien que en años de uso me triplique",
    "Que no parezca haberse queda'o sin tabique",
    "Tampoco somos tontos",
    "Incluso a los que nos mola lo suavito",
    "De vez en cuando nos gusta el pique",
    "¿Por qué no ceder y dar la razón",
    "A una feminista rompedora?",
    "¿Y si acepto mi fallo y doy borrón",
    "Porque me lo ha dicho una escritora?",
    "Ya se me han puesto en contra periodistas y doctoras",
    "Me están haciendo bullying hasta antiguas profesoras",
    "Me suena el móvil, miro y por lo visto",
    "Me regalan dos billetes para Bali con ruta en lancha motora",
    "¡Hey! Buenas tardes, tengo poca cobertura",
    "Al final, cruzando promos, he terminado en Honduras",
    "Según me han dicho, en mis menciones la cosa está dura",
    "Así que no enseño los pezones por si me censuran (oh)",
    "Que si machista, misógino opresor",
    "Que si clasista de impuestos evasor",
    "Me lloran comunistas sin la comunión",
    "¿Cómo voy a respetar a to' estos polvos sin condón?",
    "Don comedia, me hago llamar, no me suena mal",
    "¿Dónde te tengo que firmar pa' no molestar?",
    "Don Ética y Mister moral me han hecho viral",
    "Con un hilo donde cada FAV lo convierto en ca$h",
    "La dignidad podéis usar como contra argumento",
    "Para mi figura tumbar",
    "Pero es que en realidad, y ahora escuchad",
    "De verdad que lo siento, pero no paro de explotar",
    "Qué flipa'o que solo habla de pas-pas-pasta",
    "Qué pringa'o, que sepas que eres cas-cas-casta",
    "Qué pesa'o, no me importa en qué gas-gas-gastas",
    "¡Vale, me pongo el candado, BAS-BAS-BASTA!",
    "No te recomiendo pisarme lo fregado",
    "Y si lo haces, no lo borres, lo tengo capturado",
    "A mí no me tengas miedo, que ahora somos hermanos",
    "Yo el listo, tú el bastardo al que humillo por retrasado",
    "¡Hey! Buenas noches, me pillas terminando",
    "El personaje, la trama, el papel, que estoy elaborando",
    "¿Pensabas que ser tonto me salía improvisando?",
    "Me considero un genio, pero jo, te estás pasando",
    "Como ya no tengo solución",
    "Tendré que monetizarlo yo",
    "Y si pica, prueba rascándote chica",
    "Que aquí termina el capítulo"
  ],
  "blu": [
    "Lo que empezó como una broma",
    "Y un tonteo a ver qué tal",
    "Se ha convertido en un diploma",
    "Pa'l que no había que estudiar",
    "Solo domino dos idiomas",
    "Que nunca he sabido hablar",
    "Uno es orientarme hasta en Roma",
    "El otro es saber escuchar",
    "El seguro pa' ganar mil apuestas",
    "El veneno que carga mi ballesta",
    "Eres tú lo que esconde el baúl",
    "Reina de sangre azul, de familia modesta",
    "Déjame recordarte que to' lo que tenemos hecho ahora empezó sin querer",
    "Mi tiempo libre y tus vacaciones",
    "No cayeron en la cuenta",
    "De todo lo que íbamos a ser (¿y por qué?)",
    "Porque lo nuestro se moja, se rompe, se tira",
    "Anda mira si ha vuelto a crecer",
    "Solucionar lo que no funciona",
    "Es lo que hace que funcione y",
    "Se solucione sin querer",
    "Oye, préstame tu goma",
    "Que se me ha olvidado borrar",
    "Por escribirte en mil idiomas",
    "Lo que me duele si no estás",
    "Tengo aprendidos tus aromas",
    "Siempre eres mi tema del bar",
    "Cuando por la oficina asomas",
    "Ya no asimilo trabajar",
    "Que expresen lo que significa mirarte",
    "Pero no consigo sacar el valor",
    "Para ponerme delante, de tal semejante",
    "Mujer, te lo juro, joder, sé que tú no lo ves",
    "Pero déjame ser lo que nunca tuviste",
    "Y no necesitaste, pero ahora que existe",
    "No te va a doler",
    "Diez y pico soñé con hallarte y logré rescatarte",
    "De Marte y la estrella gané",
    "Si me pides la Luna por mucho que cueste",
    "Yo me las apaño y te la bajaré",
    "Como mucho morder, si vamos a correr",
    "Como poco lo sé, tranquilo, cambiaré",
    "Visto a cuatro, repite dos veces la suma perfecta",
    "Por la que pa' mí eres un 10",
    "El seguro pa' ganar mil apuestas",
    "El veneno que carga mi ballesta",
    "Eres tú lo que esconde el baúl",
    "Reina de sangre azul, de familia modesta",
    "El pasado me recuerda y molesta",
    "El futuro necesita respuestas",
    "Eres tú, mi presente eres tú",
    "Y no es casualidad, no, no es casualidad"
  ],
  "COVID-AD": [
    "En mitad de la cuarentena",
    "Solo me encuentro problemas",
    "La actitud de los que quiero",
    "Me está dando mucha pena",
    "Yo pensando en polvorones",
    "Mantecados y turrones",
    "Y en la tele solo escucho",
    "Que me tocan los cojones",
    "Navidad es la época",
    "De la felicidad",
    "De pasarla con los tuyos",
    "Y si caben muchos más",
    "Pero el covid-19",
    "No deja de molestar",
    "Y como intentes celebrarla",
    "Hermano me van a multar",
    "Santa Claus hijo puta",
    "No me trajiste la play",
    "Si te pido algo este año",
    "Dámelo al toque mi rey",
    "Por supuesto con cuidado",
    "Y respetando las medidas",
    "Tráete las manos lavadas",
    "Y los renos con mascarilla",
    "Aunque bueno dicen que",
    "Papa Noel y sus dos bolas",
    "Lo inventaron los jefes de",
    "Marketing de coca-cola",
    "Por lo tanto si no pagan",
    "Mencionarlo no me mola",
    "Es como si meto al morad",
    "Cantando la de Motorola",
    "Si en tu casa en vez del gordo",
    "Vienen los tres reyes magos",
    "Ten a mano PCR's",
    "E hidrogel en el lavabo",
    "Los niños que estén durmiendo",
    "Que los bares están abriendo",
    "Y Baltasar tiene famita",
    "De llegar alcoholizado",
    "Hablando de regalitos",
    "Nenes no toquéis el pito",
    "Que la crisis hace tiempo",
    "Que dejo de ser un mito",
    "Ser pacientes y maduros",
    "No os pongáis muy exquisitos",
    "Que al final solo necesitas",
    "Pa'l' Fortnite un mandito",
    "Ve pillando un jersey feo",
    "Quita ya al puto kidd keo",
    "Que sus temas tienen copy",
    "Y casi me como un baneo",
    "Ahora pegan villancicos",
    "Y ver nieve en la ventana",
    "Sobre to' si te has mudao'",
    "A la república andorrana",
    "Pillo hueco en el sofá",
    "Y mantita para esta semana",
    "Así con suerte parto Netflix",
    "Con la z**** de tu hermana",
    "Maratón de antena 3",
    "To' los domingos con los panas",
    "Voy a comerme más anuncios",
    "Que en mi stream por la mañana",
    "Que por cierto, to' este tema",
    "Me lo he sacado en directo",
    "Así que dame follow en insta",
    "Que tengo MDS abiertos",
    "Subo tiktoks que dan pena",
    "Pero rentan pa' la cena",
    "En fin de año si en la mesa",
    "No te tocan muchas nenas",
    "Dame tu Twitch prime"
  ],
  "el otro era yo": [
    "¿Qué ha pasa'o?",
    "Ya ha llega'o",
    "El blanquito to' flipa'o",
    "Que se come los polos en invierno",
    "Y deja pa'l verano los manteca'os",
    "Se ha olvida'o recogerla porque de camino iba to' soba'o",
    "To' centra'o en ponerla donde el senderito está to' valla'o",
    "No me cuentes historias y movidas",
    "Yo lo intento, pero es que se me olvidan",
    "Ni el orgullo, ni mi ego cabrón me brindan la razón si en el vaso me queda bebida",
    "Cántame to' lo que tú quieras",
    "Me gusta tu carita bonita, lo digo de primeras",
    "Yo de la manita vamo' pa' fuera",
    "Te llevo a la playita, solita",
    "Y miramos las palmeras",
    "Un pasito pa' a'lante, dos pasitos pa' atrás",
    "Yo que soy un liante, tú te dejas liar",
    "Un pasito pa' a'lante, dos pasitos pa' atrás",
    "Te veo interesante, no seas interesá'",
    "Un pasito pa' a'lante, dos pasitos pa' atrás",
    "Yo que soy un liante, tú te dejas liar",
    "Un pasito pa' a'lante, dos pasitos pa' atrás",
    "Te veo interesante, no seas interesá'",
    "Ya no diferencio merengue y bachata",
    "Sorry si voy lento por esta fumata",
    "Y me mata la gata con bata de plata",
    "Delata, me ata y me cata de ingrata",
    "Ya no diferencio culito y piñata",
    "Sorry si voy lento, los putos cubatas",
    "Me mata la gata con bata de plata",
    "Delata, me ata y me cata de ingrata",
    "Dura noche atrevida",
    "Tengo entrada y tú vas salida",
    "Si preguntan tú eres mi amiga",
    "No se me olvida, no se me olvida",
    "No te queda mucha saliva",
    "Pa' cumplir mis expectativas",
    "Desde abajo me entero arriba",
    "Que era mentira, que era mentira",
    "Me seduce por delante",
    "Pero me la mete doblá' detrás",
    "Tiene valor a gritar: Farsante",
    "Qué elegante vino Satán",
    "Se sabe bien el cuento",
    "No le cuesta mucho memorizar",
    "Me baja el ritmo a lento",
    "Va que no me enfado, un ratito más",
    "En mi punto de mira",
    "Te llevaré si me voy de gira",
    "Que yo ensucio mucho y tengo claro a lo que aspiras",
    "Mira, puede que no sea pa' to'a la vida",
    "Me ha conta'o Piqué que ya no está con la Shakira",
    "Oler tu aliento en movimiento",
    "El monumento más rarito de to' el convento",
    "Trae descuento (shh-shh)",
    "Nos van a echa-cha-chaar",
    "Un pasito pa' a'lante, dos pasitos pa' atrás",
    "Yo que soy un liante, tú te dejas liar",
    "Un pasito pa' a'lante, dos pasitos pa' atrás",
    "Te veo interesante, no seas interesá'"
  ],
  "mansana": [
    "Esa morena, chico, a mí me tiene loco",
    "Pero me está mirando con carita de diva",
    "Ojitos claros que iluminan los focos",
    "Te juro que enfoco y mirada perdida",
    "Me voy a callar, no voy a decirte",
    "Todo lo que te haría for free",
    "Deja de mirar, déjame seguir",
    "Que no te quiero confundir",
    "Caminaba por la feria, en el bolsillo una miseria",
    "Imaginaba que me quedaba un poco",
    "No quiero entrar en materia, pero vaya psicodelia",
    "Intolerante a la lactosa, no al choco",
    "Con todo el ruido de la gente y el zumbido permanente",
    "De un amigo que no iba bien tampoco",
    "Paro en seco de repente y un sonido a 120",
    "Es el latido de mi corazón roto",
    "Va de gitana, pero santita conmigo",
    "Sabe bailar sevillanas, sabe que no soy su amigo",
    "Esa morena, chico, a mí me tiene loco",
    "Pero me está mirando con carita de viva",
    "Ojitos claro que iluminan los focos",
    "Te juro que enfoco, mirada perdida",
    "Me voy a callar, no voy a decirte",
    "Todo lo que te haría for free",
    "Deja de mirar, déjame seguir",
    "Que no te quiero confundir",
    "Cojo una manzana, la muerdo y la tiro",
    "Cojo una manzana, la muerdo y la tiro",
    "Cojo una manzana, la muerdo y la tiro",
    "Tra', tra', tra' (tra', tra', tra')",
    "Cojo una manzana, la muerdo y la tiro (cojo una manzana, la muerdo y la tiro)",
    "Cojo una manzana, la muerdo y la tiro (cojo una manzana, la muerdo y la tiro)",
    "Cojo una manzana, la muerdo y la tiro (cojo una manzana, la muerdo y la tiro)",
    "Y si te muerdo el cuello, sorry me he perdido (y si te muerdo el cuello, sorry, me he perdido)",
    "De madrugada, pa' las casetas contigo",
    "Ponte cerquita sultana, que necesito testigos",
    "Y to' esta parte me la marco en andaluz",
    "¿Donde se ha queda'o el acento que gritaba a cuatro vientos desde el sur?",
    "Niña no me metas bulla, no me seas papa frita",
    "'Cucha Amparo un capillita en el bus",
    "Vaya pegos me está contando mi socio",
    "Me sonríe una mijilla, el otro le hace la cruz",
    "Revenía de su casa, se 'escojona con mi WhatsApp",
    "Picha, que después del tunel siempre viene la luz",
    "De madrugada, pa' las casetas contigo",
    "Ponte cerquita sultana, que necesito testigos",
    "Va de gitana, pero santita conmigo",
    "Sabe bailar sevillanas, sabe que no soy su amigo",
    "Esa morena, chico, a mí me tiene loco",
    "Pero me está mirando con carita de diva",
    "Ojitos claro que iluminan los focos",
    "Te juro que enfoco, mirada perdida",
    "Me voy a callar, no voy a decirte",
    "Todo lo que te haría for free",
    "Deja de mirar, déjame seguir",
    "Que no te quiero confundir",
    "Cojo una manzana, la muerdo y la tiro",
    "Cojo una manzana, la muerdo y la tiro",
    "Cojo una manzana, la muerdo y la tiro",
    "Cojo una manzana, la muerdo y la tiro",
    "Cojo una manzana, la muerdo y la tiro",
    "Cojo una manzana, la muerdo y la tiro",
    "Cojo una man- anda si ya me la comi'o"
  ],
  "fórmula secreta": [
    "Nunca he entendido lo de: Vivir pa' trabajar",
    "Si lo que gano al terminar me lo gasto en vivir",
    "Nunca he terminado un verano sin mirar atrás",
    "Y ahora quiero salir de aquí contigo",
    "Nunca he entendido lo de: Vivir pa' trabajar",
    "Si lo que gano al terminar me lo gasto en vivir",
    "Nunca he terminado un verano sin mirar atrás",
    "Y ahora quiero salir",
    "Pero cómo voy a encontrar mi amor, la fórmula secreta",
    "De prisa venga ya, nos la jugamos sin maletas",
    "Pilla libreta y a buscar vuelos baratos",
    "Planes pa' pasar el rato fi",
    "Si tenemos mil, solo di que si",
    "Vamos a romper platos",
    "Voy a buscar el sitio de aquel post",
    "Que me dejó enamora'o en Insta",
    "Se lo cuento, me mira, se ríe",
    "Y me enseña que ya lo tenía en su lista",
    "Y solo quiero besarte",
    "No perderte de vista",
    "Me veía un descarte",
    "Te creía más lista",
    "Y me rememoro un momento fugaz y contento",
    "Las ganas que tengo de ti si me enamoro",
    "Si me enamoro, lo siento, fue culpa del viento",
    "Que me ha arrastra'o hasta aquí",
    "Mami no buscó los motivos",
    "Ni tampoco a los culpables",
    "Sufre o disfruta conmigo",
    "Que se crucen nuestros cables",
    "De camino me ficha de artista",
    "Me la pela volar en turista",
    "No quiero ver mil, apago el móvil",
    "Si me arruino que sea de la risa",
    "Y dime, cuál es la fórmula secreta",
    "De prisa venga ya nos la jugamos sin maletas",
    "Pilla libreta y a buscar vuelos baratos",
    "Planes pa' pasar el rato fi",
    "Si tenemos mil, solo di que si",
    "Vamos a romper platos",
    "Ella solo necesita dembow pa' marcarse su terreno en la pista",
    "Siempre deja claro quién es la que manda es una abeja reina cintura de avispa",
    "Y me susurra a mí si no sabe, solo fíjate en esta loca",
    "Vale, pero ahora no grabes, que voy a comerte la boca",
    "Me susurra a mí si no sabe, solo fíjate en esta loca",
    "Vale, pero ahora no grabes, que voy a comerte la boca",
    "De camino me ficha de artista",
    "Me la pela volar en turista, no quiero ver mil",
    "Apago el móvil, si me arruino que sea de la risa, y dime",
    "Pero como voy a encontrar mi amor, la fórmula secreta",
    "De prisa venga ya nos la jugamos sin maletas",
    "Pilla libreta y a buscar vuelos baratos",
    "Planes pa' pasar el rato fi",
    "Si tenemos mil, solo di que si",
    "Vamos a romper platos",
    "Pero como voy a encontrar mi amor, la fórmula secreta",
    "De prisa venga ya nos la jugamos sin maletas",
    "Pilla libreta y a buscar vuelos baratos",
    "Planes pa' pasar el rato fi",
    "Si tenemos mil, solo di que si",
    "Vamos a romper platos"
  ],
  "ABISMO": [
    "Y ahora siento que lo nuestro se apagó",
    "Que yo quedé enredado",
    "Sin poder escapar de tu piel",
    "En la meta, cual caballo ganador",
    "Jugando a suerte el dado",
    "Sin tenerte a mi lado, qué sed",
    "Caigo en el mismo abismo",
    "Que si no nos vimos, ¿qué fuimos?",
    "Cantando otro himno, nos vimos",
    "No me quiero a mí mismo, otro vino",
    "Caigo en el mismo abismo",
    "Que si no nos vimos, ¿qué fuimos?",
    "Cantando otro himno, nos vimos",
    "No me quiero a mí mismo, otro vino",
    "Sé jugar al juego con el cora partido",
    "Sé llegar al fin, desde el principio he salido",
    "Quiero ser lo que siempre he prometido",
    "Darle a la mamá todo lo que se ha merecido",
    "To lo que ha merecido, a ese niño chico",
    "Que aún no me explico, cómo hace el perico",
    "Siempre estás en sus picos, en el mismo equipo",
    "Rompiendo los kick off, woh-woh-woh-woh",
    "Y hace tela que estoy contra la pared",
    "Tus sentidos ya no sirven pa gustarte ni pa verme",
    "Bienvenidos tus gemidos al Edén",
    "Si mi corazón lo siente porque tus ojos no ven",
    "Que no me sirve de nada ponerme 50 estados",
    "Dos mil oportunidades que mi cabeza han rallado",
    "4-20 por bandera y referente que me enseña mi reloj",
    "Recordándome to lo que te he esperado",
    "Me tropiezo una y mil veces y aunque me salga al arcén",
    "Si se derrite la nieve me estoy ahogando en un badén",
    "Una frase del Cali y el Dandee te recordaré",
    "Y es que aunque se pase toda mi vida yo te esperaré",
    "Toda mi vida yo te esperaré",
    "Y ahora siento que lo nuestro se apagó",
    "Que yo quedé enredado",
    "Sin poder escapar de tu piel",
    "En la meta, cual caballo ganador",
    "Jugando a suerte el dado",
    "Sin tenerte a mi lado, qué sed",
    "Caigo en el mismo abismo",
    "Que si no nos vimos, ¿qué fuimos?",
    "Cantando otro himno, nos vimos",
    "No me quiero a mí mismo, otro vino"
  ],
  "romilar": [
    "Es que yo tengo el boton de tu piel (romeo)",
    "Tu foto en mi cajon de papel (ricky)",
    "Porque ahora estoy empezando a caer (nono...)",
    "Porque estoy notando tu desnivel",
    "Tu piel me sabe a miel",
    "Y yo hace tiempo que ya me encontre",
    "Que ya no es como ayer",
    "Y toa esa mierda niña yo ya la olvide",
    "Ya se acabo ey ey",
    "Que nos paso ey ey ey ey",
    "Sacarte de mi recuerdo",
    "Esto es distinto lo siento",
    "Tiene acento tropical",
    "Le gusta el dominar",
    "Me quiere obligar",
    "Mezcla ron con romilar",
    "Dime que nos va a pasa a aar",
    "Bby quedas o te vaaa aa aaas",
    "Tiene acento tropical",
    "Le gusta el dominar",
    "Me quiere obligar",
    "Mezcla ron con romilar",
    "Dime que nos va a pasa a aar",
    "Bby quedas o te vaaa aa aaas",
    "Oye dime mami que nos va a pasar",
    "Si el puto tiempo no controlo cuando te voy a Olvidar",
    "Y dar 80 vueltas rapido a camara lenta",
    "Me levanto y tu te sientas",
    "Mejor tumbaditos maa",
    "Tampoco tengo la nocion de tus nociones",
    "Me conozco tus reacciones vaa no me hagas Reaccionar",
    "Que tengo mil dolores que se hacen pasar por Flores",
    "Me has sacado de mejores y yo que me queria quedar",
    "Tiene acento tropical",
    "Le gusta el dominar",
    "Me quiere obligar",
    "Mezcla ron con romilar",
    "Dime que nos va a pasar a aar",
    "Bby quedas o te vaaa aa aaaaa",
    "Tiene acento tropical",
    "Le gusta el dominar",
    "Me quiere obligar",
    "Mezcla ron con romilar",
    "Dime que nos va a pasa a aar",
    "Bby quedas o te vaaa aa aaas",
    "Baby tu dame otra salida",
    "Porque ella dice que me quiere pero eso es mentira",
    "Estoy pensando en esa hoe, no, se si me lia",
    "Mezclo romilar con ron, hoy, si que se lia",
    "Porque baby yo no te contesto",
    "Estoy mirando atrás no me encuentro en el contexto",
    "Porque eso que me das, yo, no lo tengo",
    "Baby estoy mirando atrás pero no encuentro el pretestoo",
    "Tiene acento tropical",
    "Le gusta el dominar",
    "Me quiere obligar",
    "Mezcla ron con romilar",
    "Dime que nos va a pasar a aar",
    "Bby quedas o te vaa a aaaa",
    "Tiene acento tropical",
    "Le gusta el dominar",
    "Me quiere obligar",
    "Mezcla ron con romilar",
    "Dime que nos va a pasar a aar",
    "Bby quedas o te vaaa aa aaas"
  ],
  "Parche": [
    "Han sido tantas veces viniéndome con lo mismo",
    "Maquillando tus palabras pa' alejarme del abismo",
    "Te los compro si tú me los vendes",
    "Hablo de los cuentos que forma tu mecanis-",
    "Mogollón de capítulos he abierto y me has cerrado",
    "Cien historias y aventuras",
    "Que te he escrito me has borrado",
    "Mil concursos de poesía por tu carita he ganado",
    "Pa' que acabes preguntándome porqué estoy tan rayado",
    "¿Pa qué quiero lo de antes?",
    "Así no puedo avanzar",
    "No me pintes de farsante solo porque sé actuar",
    "¿Pa' qué vas de interesante si me sé to' tu historial?",
    "No me pidas que elimine tus mensajes de Instagram",
    "¿Pa' qué quiero que levantes to' lo que vas a tirar?",
    "No me quedan más diamantes, deja ya de vacilar",
    "¿Pa' qué estudias a Descartes, si soy yo quien te va a echar?",
    "No me pidas que te cante si no me vas a escuchar",
    "¿Pa' qué te pones delante si te voy a dejar atrás?",
    "No me sirve un comandante que tiene miedo a luchar",
    "¿Pa' qué quiero verte un martes si el domingo ya no estás?",
    "No me pidas ver Mutantes si lo nuestro es Zombieland",
    "Mi especialidad, nunca ha sido la paciencia",
    "Siempre he sido de actuar por impulsos que no piensan",
    "En que puede salir mal, ignorando a mi conciencia",
    "Que ha entendido que mi nombre ya no sale en tus tendencias",
    "Me he aprendido a valorar, repasando tus patrones",
    "Me he estudiado las palabras que me dejaron lesiones",
    "¿Qué me mires o enfrentarme a los leones?",
    "De cabeza a los felinos, que tus ojos son cañones",
    "¿Pa qué quiero lo de antes?",
    "Así no puedo avanzar",
    "No me pintes de farsante solo porque sé actuar",
    "¿Pa' qué vas de interesante si me sé to' tu historial?",
    "No me pidas que elimine tus mensajes de Instagram",
    "¿Pa' qué quiero que levantes to' lo que vas a tirar?",
    "No me quedan más diamantes deja ya de vacilar",
    "¿Pa' qué estudias a Descartes, si soy yo quien te va a echar?",
    "No me pidas que te cante si no me vas a escuchar",
    "¿Pa' qué te pones delante si te voy a dejar atrás?",
    "No me sirve un comandante que tiene miedo a luchar",
    "¿Pa' qué quiero verte un martes si el domingo ya no estás?",
    "No me pidas ver Mutantes si lo nuestro es Zombieland",
    "Es que ¿pa' qué? ¿Pa' que?",
    "Si lo he intentado tantas veces que ya",
    "Ha perdido hasta la gracia",
    "Ya no encuentro motivos pa' seguir intentándolo tía",
    "Ya, ya me he cansao'",
    "Así que en fin, quédate con esto"
  ],
  "Así Es Internet (2015)": [
    "Cada mañana me informo un poco más",
    "Por las redes sociales como Twitter o Instagram",
    "Y adivina lo que he visto, lo que se lleva ahora",
    "Sacarse fotos con un vaso y una aspiradora",
    "Y es que cada semana, sale una moda nueva",
    "Algún tonto se la inventa y todos los demás la prueban",
    "Si eres tú el que no la sigue",
    "Más te vale esconderte para que no te nominen",
    "Haz planking en una silla, graba un vine mientras alguien chilla",
    "Asfíxiate comiendo canela, sube un Harlem Shake con Mandela",
    "No es por criticar, pero hay mucho postureo",
    "Y no hablo por hablar, sino por lo que aquí veo",
    "No estoy diciendo que lo hagáis mal",
    "Sino que inventáis las reglas para salir genial",
    "Si de verdad es la foto que nunca subirías no vale una foto maquillá' y sin espinillas",
    "Y si el reto consiste en tirarte a la piscina",
    "Salta al agua y deja de posar en la sombrilla",
    "En YouTube la moda es criticar a los más grandes (elrubius se copia de PewDiePie)",
    "O dibujar tu vida en un folio con lápiz (de pequeño me caí desde un avión...)",
    "Algunos se han vendido, ya no molan como antes (me encantan las oreo)",
    "Y te lo cuentan en cincuenta cosas sobre mí (número uno: No tengo amigos)",
    "Ahora las fotos van a otro ritmo",
    "Tienen que ser con palo o si no: no es lo mismo",
    "Dorado y blanco o azul y negro qué más da el vestido",
    "Todo el mundo rallado por algo tan sencillo",
    "A los aventureros, os doy un consejillo",
    "Saltad en trampolines o si no desde el bordillo",
    "Lo digo porque los balcones son para asomarse",
    "Pero si te la juegas solo sirven pa' matarse",
    "Y bueno, así para acabar, recuerdo que también estoy en Twitter e Instagram",
    "Espero que hayas disfrutado el vídeo y la canción porque lo valen",
    "Y para irme me marco un Ice Bucket Challenge"
  ],
  "Así Es Internet (2016)": [
    "Ya ha pasado un año de la última canción",
    "Donde recopilo las modas que en todo internet son una obsesión",
    "Parece difícil buscar nuevas tendencias que hayan triunfado",
    "Pero es que cualquier tontería en la red este año ha arrasado",
    "Me pillas vicia'o al Slither.io",
    "Dos horas jugando y maldito crío",
    "Me mata y se cree que es una pasada",
    "Pero ahora lo rodeo que esa es mi jugada",
    "Y hablando de gusanos, cuida'o con los huevos",
    "Mejor cómetelos no pruebes nada nuevo",
    "Lo digo porque si vas a experimentar",
    "En unos días un homúnculo puedes crear",
    "Y no te rías, ya que si te ríes pierdes",
    "Una carcajada y el polvo muerdes",
    "Vale, quizá soy algo exagerado",
    "Pero yo sin pelos en la pierna he acabado",
    "¿Acaso eres una persona peluda?",
    "Tranquila, yo me encargo de ser tu ayuda",
    "Ponte musiquita y baila así en plan postureo",
    "Que con algo de magia eso se cura",
    "Aprovecha que estás junto a tu amigo",
    "Para hacer un FaceSwap, así te lo digo",
    "Cámbiate la cara con tu hermana, con tu amigo",
    "Con tu perro, o incluso con tu vecino",
    "Ve al baño corriendo y abre tu cartera",
    "Por fin vas a dar uso de alguna manera",
    "A ese preservativo que lleva tiempo caducado",
    "Y al menos el reto del condón lo has logrado",
    "La broma de la mierda falsa en un cuarto de baño",
    "Era graciosa cuando las víctimas no eran preparadas",
    "Llevan en YouTube aproximadamente más de un año",
    "Y casi todas las que veo son falsas, no valen nada",
    "¡Salseo! No sé quién se ha lia'o con no sé cuántas",
    "¿Qué más da joder? ¡Su contenido me encanta!",
    "Dejad de buscar intimidades y secretos",
    "Que aquí tos' somos personas ligar no es ningún invento",
    "Maldito, el creador de este juego tan adictivo",
    "La gente se supera a un ritmo preocupante",
    "A la par que divertido",
    "Por fin el SimSimi ya no está de moda",
    "Y podemos hablar de otra cosa",
    "Tremendo follón ha montado el limón",
    "Era una aplicación desastrosa",
    "La gente se entretiene viendo objetos aplastados",
    "Cuatro rusos y una prensa famosos se han acostado",
    "Llamo al 666 y me contesta satanás",
    "Aunque lo cierto sea que los que graban esto sean los auténticos fantasmas",
    "Colarse en la casa del vecino es la meta de un videojuego",
    "¿Qué esconderá tras esa puerta?",
    "Lo descubriremos luego",
    "Los círculos rojos y las flechas han triunfado",
    "Los reyes del clickbait estos meses mucho han cobrado",
    "Este año ha sido intenso",
    "Y ya casi se ha acabado",
    "Imitando a maniquíes todo el mundo ha terminado",
    "¡Hey! ¿Cómo se llamaba el señor que luchaba en la John Cena?"
  ],
  "Querido Youtube": [
    "Bien Youtube, tú y yo tenemos que hablar",
    "AVISO en este vídeo el tono un poquito subido está",
    "Y es que me ha dado por echar unos meses la vista atrás",
    "Y claro, la plataforma se deshace cada vez más",
    "Yo llevo aquí desde el comienzo, que mi canal pegara el boom",
    "Hace casi dos años no es mi lienzo para mi obra expresar, mi mensaje dar",
    "Abrid los oídos y cerrad los ojos, os vais a cagar",
    "Resulta que esta página se muere poco a poco",
    "No os dais cuenta pero creedme si digo que no estoy loco",
    "Y ruego tranquilidad, si podéis pillad palomitas",
    "Aunque lo que voy a soltar no te va a saber a poco",
    "Quiero echar la vista atrás hacia una época mejor",
    "Digamos, yo qué sé, ¿2012? Joder, cuánto dolor",
    "El iconito rojo empezaba a volar de boca en boca",
    "Y con el paso del tiempo, esta red social es lo peor",
    "Tenías visitas, sí, subieras lo que subieras",
    "No había guerras ni batallas pa’ que la gente te viera",
    "Lo importante era tener un vídeo que a ti te gustara",
    "Aunque tuvieras 120 visitas, eran sinceras",
    "Poco a poco la comunidad junta se fue adaptando",
    "Cada loco con su tema y su canal iba avanzando",
    "No sé en qué momento exacto ocurrió pero pasó",
    "El fenómeno “youtuber” se había acabado arraigando",
    "Aquí en España sólo eran 4 o 5 haciendo el tonto",
    "Que sin darse cuenta entretenían a muchas personas",
    "Las cifras de suscriptores empezaron a subir pronto",
    "Y las visitas… Esas no hay quien se las coma",
    "Pasaron algunos meses de puro entretenimiento",
    "Sin otros factores, la creatividad era un buen invento",
    "Pero claro la gente estudiaba y esto no rentaba",
    "Así que la publicidad dijo “ya he llegao, lo siento”",
    "No sonaba mal, ¿anuncios que se pueden saltar?",
    "Al menos supera a la tele, aunque… ¿quién usa eso ya?",
    "En pocos días la gente se acostumbró al nuevo formato",
    "Y lo que no sabían es que a día de hoy eso es mortal",
    "Los primeros avispaos’ tiraron por los videojuegos",
    "¿Gameplays de 30 minutos? Encima en 2.0",
    "Cuantos más subieras, más dinerito, eso era sencillo",
    "Y los jodidos niños rata: ¡sube otro, te lo ruego!",
    "No hace falta ser muy listo para volar por la mente",
    "De un niñato “gamer” que en su casa se rie de la gente",
    "Y ojo no critico a los que juegan sólo por disfrute",
    "Sino a los gritones que quieren ser ricos repelentes",
    "Si alguno era muy querido se abría un canal de vlogs",
    "Para contar básicamente su vida, eso es lo mejor",
    "Miles y miles de visitas en vídeos de diez minutos",
    "De tu ídolo comiendo cereales en un bol",
    "Para gustos los colores, no es lo que estoy criticando",
    "Yo me quejo del camino que youtube está tomando",
    "Ya que no debemos de olvidar que no es más que una empresa",
    "Y su cometido final, es ir billetes pillando",
    "Trabajando más en logos y diseños sin sentido",
    "Que en los métodos de promo y algoritmos invertidos",
    "No me extraña que cuando me meta en vídeos del momento",
    "Me aparezcan vídeos de to’ tipo menos divertidos",
    "Ahora somos centenares y ya está todo subido",
    "¿De verdad sigues llamándote creador de contenido?",
    "Yo veo  fieras con contactos que de la forma más guarra",
    "Sin pensarlo por dos pavos  venderían a sus “amigos”",
    "Te da por subir un tag de novios con una chiquilla",
    "Cuyas tetas para ver no necesitas ni lentillas",
    "Pero claro, qué vas a decir, es amor verdadero",
    "Aunque la conocieras el otro día en un bar de Sevilla",
    "Luego están los de los “Challenges”,  dicen que trabajan duro",
    "en su canal, aunque la edición se les de como el culo",
    "no son más que relleno para cubrir los meses buenos",
    "Os lo dice un veterano que subidos tiene algunos",
    "¿Tanto cuesta dar la cara y aceptar la triste realidad",
    "de responder en entrevistas con sinceridad?",
    "Me refiero si te preguntan si lo haces por dinero",
    "Di que sí, sonrisita y a otra cosa, subnormal",
    "Tampoco os voy a engañar, esto está monetizado",
    "Con suerte los derechos de la canción no están pillados",
    "Pero yo lo admito, para mi youtube es un trabajo",
    "Al mismo tiempo que un juguete para hipócritas forrados",
    "Podría seguir echando caquita a la comunidad",
    "Pero para escarbar en la mierda me voy yendo ya",
    "Lo dicho: sed buenos y tened el AdBlock desactivado",
    "No jodáis el chiringuito que estos tienen que cobrar",
    "Hacía tiempo que no me expresaba sin limitaciones",
    "Es que estoy algo cansado de esta panda de mamones",
    "Tengo twitter e instagram por si queréis ver más cosillas",
    "Y antes de insultar, querido hater…",
    "Da un dislike, cojones."
  ],
  "Soy Un Tryhard": [
    "¿Por qué salgo de pisos con diez kills",
    "Y no encuentrooo ningún botiquín?",
    "¡He reventado a tres o cuatro teams",
    "Para que me mate un sin skin!",
    "Voy con el pase a nivel 100",
    "Mi tambor suena fetén",
    "Tras seis horas en creativo",
    "Me salen los 90s bien",
    "Entró al lobby a vacilar",
    "A quien sea que vea correr",
    "Que sepan que llevo aquí",
    "Desde la temporada 3",
    "Piensa que el bus va despacio",
    "Necesita dropearse pronto",
    "Ya se ha cargado el espacio",
    "Y ha acabado abriendo el paraguas por tonto",
    "No me importan las kills",
    "Yo solo quiero ganar",
    "Voy a buscar un boloncho",
    "Cerca de Pico Polar",
    "Creo que hay alguien en mi zona",
    "Y yo no tengo material",
    "Así que pico un cuarto de ahora",
    "Pa' ponerme full metal",
    "Solo usa la skin de futbolista",
    "No se puede ser más tryhard",
    "Si te pilla la altura en su isla",
    "Hasta el mes que viene no te baja",
    "¿Por que no tengo un solo ladrillo?",
    "Nooo funciona el sifón",
    "Desde que lo quitaron",
    "No soy yo",
    "Si en arena no gano nada",
    "Me voy a buscar privadas",
    "Ya que todas mis misiones",
    "Llevan semanas pasadas",
    "Si el streamer solo deja unirse",
    "A los que están suscritos",
    "Tu vaya mierda de personalizadas",
    "¿Como llevas el competitivo?",
    "400 puntos en arena",
    "¿En un boloncho escondido?",
    "Me llama mi madre pa' la cena",
    "Me dicen w-key",
    "Pero no tienen razón",
    "Si me aburro simplemente",
    "Te' rusheo sin compasión",
    "Me la suda la tormenta",
    "Una kill no se perdona",
    "Me hago dieciséis 90s",
    "Y que nos mate la zona",
    "Vengo de mirar su Twitter",
    "Se pasa tol' día llorando",
    "En su nombre pone revert",
    "Se ríe de ti si juegas con mando",
    "¿Por que ya no puedo dar doscientos?",
    "Laaa pump la han quitado",
    "Quiero pasarme al apex",
    "O hasta al lol",
    "Pero aún me queee-dan dos mil pavos"
  ],
  "50 Rimas Sobre Mi": [
    "Nunca me ha gustado hablar de mi vida privada, pero por acercarme a vosotros creo que no pasará nada.",
    "Aquí en youtube esto es 50 cosas sobre mi, pero lo típico no me gusta, así que yo lo hago así:",
    "1-No me gusta el fútbol, lo veo una tontería",
    "2-Desde que nací me faltan dos dientes de aquí de arriba",
    "3-No me he roto ningún hueso",
    "4-Creo que nunca me han pegado",
    "5-Y casi nunca me arrepiento de mis-errores del pasado",
    "6-Hablando de chicas las prefiero morenas bajitas (es un tópico que tengo y eso nadie me lo quita)",
    "7-Pa' comer una hamburguesa o una pizza barbacoa y si metes la mano en mi comida te la corto toa'",
    "8-Mi única manía es morderme fuerte los dedos",
    "9-Y si os digo la verdad no tengo novia porque puedo",
    "10-Intento ir al cine al menos un día por semana pero aunque sea guapo y rico cuestan mucho las entradas",
    "11-Nunca he estado en un concierto",
    "12-Miro muy poco la hora",
    "13-Y la gente creída y que aparenta no me mola",
    "14-Cuando quiero contar algo tiene que ser en la calle pa explicarle a la persona cómo fueron los detalles",
    "15-No me gusta que me miren fijamente cuando hablo pero el centro de atención sí que me gusta guardarlo",
    "16-Odio que me repitan lo mismo varias veces y por dios si estoy comiendo no preguntes idioteces",
    "17- Meee rio muy fácilmente pero pocas cosas me hacen gracia, pienso que la risa siempre es la mejor terapia",
    "18-Me interesa mucho el mundo de la mente y de los sueños aunque luego pa' dormirme tengo que poner empeño",
    "19-Solo considero que tenga tres amigos de verdad pero también conozco a mucha gente que me cae genial",
    "20-A veces pienso que mi vida es un programa de la tele con mil cámaras ocultas y la gente se entretiene",
    "21-No sé por qué siempre tengo la nariz entaponada",
    "22-Refiriéndome a la ropa no sigo las modas caras",
    "23-Para mi “importante” es lo que para otro una tontería",
    "24-Y si estoy mal pongo música y se arregla el día",
    "25-Pienso que la sociedad está un poco perdida, los niños con doce años casi todo lo asimilan",
    "26-Y la educación se centra en hacernos aprender cosas de memoria y no entenderlas que es la base de esta historia",
    "27-Tengo muy pocos caprichos, mi teléfono el más caro",
    "28-Creo que alguna vez lo he dicho pero al fútbol soy muy malo",
    "29-Y si quieres pillarme en algún tema concreto ponme algún ejercicio de mates y lo fallo lo prometo",
    "30-Hablando de clases la de música no la entendía, te hacían tocar la flauta aunque tú no querías. Hace unos cuántos años me enganché a un gran instrumento que a día de hoy sigo tocando y es la batería",
    "31-Prefiero los días pa' descansar y noches productivas",
    "32-Cuando el sol se está yendo salen buenas fotografías",
    "33-No me gusta ver la tele, creo que en la red está todo y los anuncios cada vez son más pesados",
    "34-¡Ah! De ningún modo me quedo callado cuando pienso algo (esto es genial pero por su culpa mal también lo he pasado)",
    "35-Cuando quiero dormir es cuando menos sueño me entra",
    "36-Y soy de esa clase de personas que no se concentra",
    "37-En los exámenes acabo rápido pero no los entrego hasta que alguien se levanta y lo entrega primero",
    "38-Y la importancia que tienen para mí las redes sociales: twitter, instagram y snapchat en ese orden ya lo sabes",
    "39-Empece en youtube subiendo cámaras ocultas",
    "40-Y aunque tengo pocos vídeos to lo que subo me gusta",
    "41-Que me masajeen los hombros o la cabeza me puede",
    "42-Y cuando me pongo el pijama de casa nadie me mueve",
    "43-Mi ciudad favorita es Nueva York, no hay quien la supere",
    "44-Y me encanta hacerme fotos con la gente que me quiere",
    "45-Hace tiempo pensaba que las críticas dolerían",
    "46-Pero cada vez hay menos  y veo mucha simpatía",
    "47-Gracias Manu por el viaje, hemos conseguido vivir",
    "48-Y gracias Samu por la base, os dejo su canal aquí",
    "49-Cuarenta y nueve datos de mi vida ya conoces",
    "50-Y el cincuenta es este vídeo que yo espero que lo gozes"
  ],
  "FRIKY": [
    "Another hit, ricky",
    "Another hit, ricky",
    "Con DJ carlos serrano en este tema que se llama: Friky",
    "Le escribo un WhatsApp y ella me bloquea",
    "Le pego un toque y ella me lo cuelga",
    "Dice que soy un incordio pero yo no le creo",
    "Y es que algo me pica cada vez que la veo feo",
    "Entro a la fiesta y lo que yo quiero",
    "Es hablar contigo nena pero yo no puedo",
    "No puedo, me dice yo no quiero",
    "Déjame tranquila yo no entiendo cómo eres tan",
    "Friky friky friky friky friky",
    "Me ha llamado friky friky friky friky friky",
    "Si yo lo intento por la izquierda",
    "Me da con la derecha",
    "No sé lo que le pasa",
    "Pero yo la quiero enamorar",
    "Ricky ricky ricky ricky ricky",
    "Yo me llamo ricky ricky ricky ricky ricky",
    "Ella me ve como una mierda",
    "Me va a hacer una brecha",
    "No sé lo que le pasa",
    "Conmigo ella no quiere ni hablar",
    "Tengo una orden de alejamiento y no hago caso",
    "Ella me mira y me grita eres un payaso",
    "Y aunque lo intente al final me dice paso",
    "Pues no me aparto ¿cuál es tu retraso?",
    "Why me insultas y te das la vuelta pero sin mirarme",
    "Soy muy guay, ¿pero qué tengo que hacer para enamorarla a usted?",
    "Porfa dame tu insta, o tu WhatsApp, en Twitter sígueme",
    "Yo voy a seguirte en Snapchat",
    "Déjame tranquila yo no entiendo cómo eres tan",
    "Friky friky friky friky friky",
    "Me ha llamado friky friky friky friky friky",
    "Si yo lo intento por la izquierda",
    "Me da con la derecha",
    "Me vuelvo a mi casa",
    "Pero yo la voy a conquistar",
    "Ricky ricky ricky ricky ricky",
    "Yo me llamo ricky ricky ricky ricky ricky",
    "Ella me ve como una mierda",
    "Me va a hacer una brecha",
    "Respóndeme algún WhatsApp",
    "Me manda el emoji de matar",
    "Nena tú no sabes que mi corazón me guía",
    "Si sigues pasando mi cabeza está vacía",
    "Y yo, contigo yo me quiero casar",
    "Y tú, lo oyes te vas corriendo y gritas",
    "Le mando un tuit y ella me reporta",
    "Le hablo por Facebook y ella me denuncia",
    "Sigo cantando en el baño porque me meo",
    "Desde la ventana de mi cuarto la veo feo",
    "Creo que lo voy a dejar, sin novia me quedo",
    "Hay muchos peces en el mar pero yo no quiero",
    "No quiero, repito yo no quiero",
    "Pero es que esa chica a mí solo me ve como un",
    "Friky friky friky friky friky",
    "Solo como un friky friky friky friky friky",
    "Si yo lo intento por la izquierda",
    "Me da con la derecha",
    "No se lo que le pasa",
    "Pero se acabó el acosar",
    "Ricky ricky ricky ricky ricky",
    "Yo me llamo ricky ricky ricky ricky ricky",
    "Ella me ve como una mierda",
    "Me va a hacer una brecha",
    "No se lo que le pasa",
    "Pero la voy a dejar marchar",
    "Un día me la encuentro, casi ni la miro pero",
    "Conmigo creo que quiere hablar",
    "Vuelve la esperanza, parece que me quiere",
    "Y no me vuelvas a mirar",
    "Ay, ricardo edición oh oh oh oh"
  ]
};
