window.RICKY_SONGS = [
  { id: "aN_W_067gng", title: "ir - rickyedit", duration: 151, year: 2026 },
  {
    id: "T585RNq__yE",
    title: "si mañana - rickyedit",
    duration: 180,
    year: 2023,
  },
  {
    id: "ex2LiPxh0WM",
    title: "diva virtual - rickyedit",
    duration: 156,
    year: 2023,
  },
  {
    id: "4Qeh6m6PlvM",
    title: "lo siento - rickyedit",
    duration: 171,
    year: 2023,
  },
  {
    id: "zXRKTawGu0g",
    title: "rango superior - rickyedit ft. magus",
    duration: 194,
    year: 2023,
  },
  { id: "5faRgy2IleU", title: "hoa - rickyedit", duration: 210, year: 2022 },
  {
    id: "nVYSD4LBaU8",
    title: "prioridad - rickyedit",
    duration: 138,
    year: 2022,
  },
  {
    id: "V7UM3kGvO8g",
    title: "otra vida - rickyedit",
    duration: 167,
    year: 2022,
  },
  {
    id: "ID8-xPRryac",
    title: "quema - rickyedit ft. esfin",
    duration: 200,
    year: 2022,
  },
  { id: "XwOc2gWuB0A", title: "paqué - rickyedit", duration: 175, year: 2022 },
  {
    id: "Y0VM6DtwM8g",
    title: "caliente - rickyedit",
    duration: 176,
    year: 2022,
  },
  {
    id: "VdWLkkSa1Ic",
    title: "noche - rickyedit (ft. betru)",
    duration: 177,
    year: 2022,
  },
  {
    id: "l52iEsdpkEA",
    title: "badabadún - rickyedit",
    duration: 193,
    year: 2022,
  },
  {
    id: "ldAilzWJ52w",
    title: "y más allá - rickyedit",
    duration: 170,
    year: 2022,
  },
  { id: "qDa73O31o1g", title: "casa - rickyedit", duration: 146, year: 2022 },
  {
    id: "92ctUKF4HwA",
    title: "gourmet - rickyedit",
    duration: 161,
    year: 2022,
  },
  {
    id: "WCLlrcJbhqk",
    title: "en verdad - rickyedit",
    duration: 170,
    year: 2022,
  },
  { id: "8JHI-61rBF8", title: "por ti - rickyedit", duration: 149, year: 2022 },
  {
    id: "U86m6GyhlqE",
    title: "mi habitación - rickyedit",
    duration: 167,
    year: 2022,
  },
  { id: "iE5ilEkc9wI", title: "era - rickyedit", duration: 172, year: 2022 },
  {
    id: "I2xRwldQ1HM",
    title: "u banned - rickyedit",
    duration: 147,
    year: 2021,
  },
  {
    id: "GMU1WqIOOzI",
    title: "4k/mes - RickyEdit ft. MateoZ",
    duration: 191,
    year: 2021,
  },
  {
    id: "Ou_tmc5JE0E",
    title: "mamisabesqno - dripseasonX ft. rickyedit",
    duration: 277,
    year: 2021,
  },
  {
    id: "wBoE1_-QZ3M",
    title: "navimal - rickyedit",
    duration: 169,
    year: 2021,
  },
  {
    id: "ymWqM09Xs0w",
    title: "quelamamen - rickyedit",
    duration: 139,
    year: 2021,
  },
  {
    id: "D2rfEVnRfvQ",
    title: "blu",
    duration: 155,
    year: 2023,
  },
  {
    id: "wAZyEvWDbm8",
    title: "COVID-AD (Villancico RickyEdit)",
    duration: 150,
    year: 2020,
  },
];
